ALTER TABLE "audit_logs"
  ADD COLUMN "visibility" character varying NOT NULL DEFAULT 'visible';

CREATE INDEX IF NOT EXISTS "auditlog_visibility_created_at"
  ON "audit_logs" ("visibility", "created_at" DESC, "id" DESC);

CREATE TABLE IF NOT EXISTS "audit_visibility_defaults" (
  "key" character varying NOT NULL,
  "strategy" character varying NOT NULL DEFAULT 'visible',
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_by" bigint NULL,
  "updated_by_name" character varying NOT NULL DEFAULT '',
  PRIMARY KEY ("key")
);

CREATE TABLE IF NOT EXISTS "audit_visibility_overrides" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "source" character varying NOT NULL,
  "action_key" character varying NOT NULL,
  "strategy" character varying NOT NULL DEFAULT 'visible',
  "description" character varying NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "created_by" bigint NULL,
  "created_by_name" character varying NOT NULL DEFAULT '',
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_by" bigint NULL,
  "updated_by_name" character varying NOT NULL DEFAULT '',
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "audit_visibility_overrides_source_action_key"
  ON "audit_visibility_overrides" ("source", "action_key");
CREATE INDEX IF NOT EXISTS "audit_visibility_overrides_strategy"
  ON "audit_visibility_overrides" ("strategy");

COMMENT ON COLUMN "audit_logs"."visibility" IS '审计记录可见性策略，visible 表示默认展示，hidden 表示默认隐藏，ignore 仅用于写入前策略决策';

COMMENT ON TABLE "audit_visibility_defaults" IS '审计事件可见性默认策略表（审计模块）';
COMMENT ON COLUMN "audit_visibility_defaults"."key" IS '默认策略作用域键，当前固定为全局策略键';
COMMENT ON COLUMN "audit_visibility_defaults"."strategy" IS '默认可见性策略，支持 visible 和 hidden，ignore 仅用于覆盖策略决策';
COMMENT ON COLUMN "audit_visibility_defaults"."updated_at" IS '默认策略最近更新时间';
COMMENT ON COLUMN "audit_visibility_defaults"."updated_by" IS '最近更新默认策略的用户 ID，为空表示系统写入';
COMMENT ON COLUMN "audit_visibility_defaults"."updated_by_name" IS '最近更新默认策略的用户名或显示名快照';

COMMENT ON TABLE "audit_visibility_overrides" IS '审计事件可见性覆盖策略表（审计模块）';
COMMENT ON COLUMN "audit_visibility_overrides"."id" IS '主键 ID';
COMMENT ON COLUMN "audit_visibility_overrides"."source" IS '审计事件来源类型，如 REQUEST、SECURITY_EVENT 或 DOMAIN_EVENT';
COMMENT ON COLUMN "audit_visibility_overrides"."action_key" IS '单个审计动作键，按标准化 action/eventType 精确匹配';
COMMENT ON COLUMN "audit_visibility_overrides"."strategy" IS '覆盖后的可见性策略，支持 visible、hidden 和 ignore';
COMMENT ON COLUMN "audit_visibility_overrides"."description" IS '覆盖策略的补充说明';
COMMENT ON COLUMN "audit_visibility_overrides"."created_at" IS '覆盖策略创建时间';
COMMENT ON COLUMN "audit_visibility_overrides"."created_by" IS '创建覆盖策略的用户 ID，为空表示系统写入';
COMMENT ON COLUMN "audit_visibility_overrides"."created_by_name" IS '创建覆盖策略的用户名或显示名快照';
COMMENT ON COLUMN "audit_visibility_overrides"."updated_at" IS '覆盖策略最近更新时间';
COMMENT ON COLUMN "audit_visibility_overrides"."updated_by" IS '最近更新覆盖策略的用户 ID，为空表示系统写入';
COMMENT ON COLUMN "audit_visibility_overrides"."updated_by_name" IS '最近更新覆盖策略的用户名或显示名快照';

INSERT INTO "audit_visibility_defaults" (
  "key",
  "strategy",
  "updated_at",
  "updated_by",
  "updated_by_name"
) VALUES (
  'global',
  'visible',
  NOW(),
  NULL,
  'system'
)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "audit_visibility_overrides" (
  "source",
  "action_key",
  "strategy",
  "description",
  "created_at",
  "created_by",
  "created_by_name",
  "updated_at",
  "updated_by",
  "updated_by_name"
) VALUES
  ('REQUEST', 'POST /api/auth/refresh', 'hidden', '默认隐藏刷新令牌轮换请求，减少审计页面中的令牌刷新噪音。', NOW(), NULL, 'system', NOW(), NULL, 'system'),
  ('SECURITY_EVENT', 'auth.token.expired', 'hidden', '默认隐藏可自动恢复的访问令牌过期事件，保留证据但不进入默认审计读面。', NOW(), NULL, 'system', NOW(), NULL, 'system')
ON CONFLICT ("source", "action_key") DO UPDATE SET
  "strategy" = EXCLUDED."strategy",
  "description" = EXCLUDED."description",
  "updated_at" = NOW(),
  "updated_by" = EXCLUDED."updated_by",
  "updated_by_name" = EXCLUDED."updated_by_name";
