export const APPLICATION_ROUTE_PATH = {
  LIST: '/applications',
  CREATE_IMPORT: '/applications/create/import',
  CREATE: '/applications/create',
  CREATE_RUNTIME_TARGET: '/applications/create/runtime-target',
  CREATE_SOURCE: '/applications/create/source',
  CREATE_DISCOVERY: '/applications/create/discovery',
  CREATE_BLANK: '/applications/create/blank',
  CREATE_TEMPLATE: '/applications/create/template',
  CREATE_TEMPLATE_DETAIL: '/applications/create/template/:templateId',
  TEMPLATES: '/applications/templates',
  TEMPLATE_CREATE: '/applications/templates/create',
  TEMPLATE_DETAIL: '/applications/templates/:templateId',
  DETAIL: '/applications/:applicationId',
  CONFIGURATION_WORKSPACE: '/applications/:applicationId/configuration',
} as const;
