/** Docker 镜像删除的稳定逐项错误码；服务端将 daemon 原始错误归类后返回这些值。 */
export const DOCKER_IMAGE_REMOVE_ERROR_CODES = {
  IMAGE_REFERENCED_BY_MULTIPLE_TAGS: 'IMAGE_REFERENCED_BY_MULTIPLE_TAGS',
  IMAGE_IN_USE: 'IMAGE_IN_USE',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  DOCKER_RUNTIME_UNAVAILABLE: 'DOCKER_RUNTIME_UNAVAILABLE',
  DOCKER_TIMEOUT: 'DOCKER_TIMEOUT',
  DOCKER_COMMUNICATION_ERROR: 'DOCKER_COMMUNICATION_ERROR',
  UNKNOWN: 'UNKNOWN',
} as const;

export type DockerImageRemoveErrorCode =
  (typeof DOCKER_IMAGE_REMOVE_ERROR_CODES)[keyof typeof DOCKER_IMAGE_REMOVE_ERROR_CODES];
