// Package runtimetargetopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package runtimetargetopenapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetRuntimeTargets401JSONResponseBodySuccess.
const (
	GetRuntimeTargets401JSONResponseBodySuccessFalse GetRuntimeTargets401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTargets401JSONResponseBodySuccess enum.
func (e GetRuntimeTargets401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTargets401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetRuntimeTargets403JSONResponseBodySuccess.
const (
	GetRuntimeTargets403JSONResponseBodySuccessFalse GetRuntimeTargets403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTargets403JSONResponseBodySuccess enum.
func (e GetRuntimeTargets403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTargets403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetRuntimeTargets500JSONResponseBodySuccess.
const (
	GetRuntimeTargets500JSONResponseBodySuccessFalse GetRuntimeTargets500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTargets500JSONResponseBodySuccess enum.
func (e GetRuntimeTargets500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTargets500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetRuntimeTarget401JSONResponseBodySuccess.
const (
	GetRuntimeTarget401JSONResponseBodySuccessFalse GetRuntimeTarget401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTarget401JSONResponseBodySuccess enum.
func (e GetRuntimeTarget401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTarget401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetRuntimeTarget403JSONResponseBodySuccess.
const (
	GetRuntimeTarget403JSONResponseBodySuccessFalse GetRuntimeTarget403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTarget403JSONResponseBodySuccess enum.
func (e GetRuntimeTarget403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTarget403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetRuntimeTarget500JSONResponseBodySuccess.
const (
	GetRuntimeTarget500JSONResponseBodySuccessFalse GetRuntimeTarget500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetRuntimeTarget500JSONResponseBodySuccess enum.
func (e GetRuntimeTarget500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetRuntimeTarget500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostRuntimeTargetRefresh401JSONResponseBodySuccess.
const (
	PostRuntimeTargetRefresh401JSONResponseBodySuccessFalse PostRuntimeTargetRefresh401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostRuntimeTargetRefresh401JSONResponseBodySuccess enum.
func (e PostRuntimeTargetRefresh401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostRuntimeTargetRefresh401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostRuntimeTargetRefresh403JSONResponseBodySuccess.
const (
	PostRuntimeTargetRefresh403JSONResponseBodySuccessFalse PostRuntimeTargetRefresh403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostRuntimeTargetRefresh403JSONResponseBodySuccess enum.
func (e PostRuntimeTargetRefresh403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostRuntimeTargetRefresh403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostRuntimeTargetRefresh500JSONResponseBodySuccess.
const (
	False PostRuntimeTargetRefresh500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostRuntimeTargetRefresh500JSONResponseBodySuccess enum.
func (e PostRuntimeTargetRefresh500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetRuntimeTargetsParams defines parameters for GetRuntimeTargets.
type GetRuntimeTargetsParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetRuntimeTargets401JSONResponseBodySuccess defines parameters for GetRuntimeTargets.
type GetRuntimeTargets401JSONResponseBodySuccess bool

// GetRuntimeTargets403JSONResponseBodySuccess defines parameters for GetRuntimeTargets.
type GetRuntimeTargets403JSONResponseBodySuccess bool

// GetRuntimeTargets500JSONResponseBodySuccess defines parameters for GetRuntimeTargets.
type GetRuntimeTargets500JSONResponseBodySuccess bool

// GetRuntimeTargetParams defines parameters for GetRuntimeTarget.
type GetRuntimeTargetParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetRuntimeTarget401JSONResponseBodySuccess defines parameters for GetRuntimeTarget.
type GetRuntimeTarget401JSONResponseBodySuccess bool

// GetRuntimeTarget403JSONResponseBodySuccess defines parameters for GetRuntimeTarget.
type GetRuntimeTarget403JSONResponseBodySuccess bool

// GetRuntimeTarget500JSONResponseBodySuccess defines parameters for GetRuntimeTarget.
type GetRuntimeTarget500JSONResponseBodySuccess bool

// PostRuntimeTargetRefreshParams defines parameters for PostRuntimeTargetRefresh.
type PostRuntimeTargetRefreshParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostRuntimeTargetRefresh401JSONResponseBodySuccess defines parameters for PostRuntimeTargetRefresh.
type PostRuntimeTargetRefresh401JSONResponseBodySuccess bool

// PostRuntimeTargetRefresh403JSONResponseBodySuccess defines parameters for PostRuntimeTargetRefresh.
type PostRuntimeTargetRefresh403JSONResponseBodySuccess bool

// PostRuntimeTargetRefresh500JSONResponseBodySuccess defines parameters for PostRuntimeTargetRefresh.
type PostRuntimeTargetRefresh500JSONResponseBodySuccess bool
