CREATE TABLE registry_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_ref VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  endpoint VARCHAR(512) NOT NULL,
  credential_ref VARCHAR(255) NULL,
  availability BOOLEAN NOT NULL DEFAULT false,
  system_managed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_registry_connections_live_ref
ON registry_connections (connection_ref)
WHERE deleted_at = 0;

CREATE TABLE artifact_repositories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id BIGINT NOT NULL REFERENCES registry_connections(id) ON DELETE RESTRICT,
  repository_ref VARCHAR(255) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  allow_push BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_artifact_repositories_live_connection_ref
ON artifact_repositories (connection_id, repository_ref)
WHERE deleted_at = 0;

CREATE INDEX idx_artifact_repositories_live_connection
ON artifact_repositories (connection_id, repository_ref)
WHERE deleted_at = 0;

CREATE TABLE artifact_repository_user_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES artifact_repositories(id) ON DELETE RESTRICT,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_artifact_repository_user_assignments_repository_user
ON artifact_repository_user_assignments (repository_id, user_id);

CREATE INDEX idx_artifact_repository_user_assignments_live_actor
ON artifact_repository_user_assignments (user_id, repository_id)
WHERE deleted_at = 0;

COMMENT ON TABLE registry_connections IS '外部镜像仓库连接与健康状态事实表';
COMMENT ON COLUMN registry_connections.id IS '镜像仓库连接内部主键';
COMMENT ON COLUMN registry_connections.connection_ref IS '供平台引用的镜像仓库连接稳定标识';
COMMENT ON COLUMN registry_connections.display_name IS '镜像仓库连接管理界面展示名称';
COMMENT ON COLUMN registry_connections.provider IS '外部镜像仓库提供方稳定标识';
COMMENT ON COLUMN registry_connections.endpoint IS '仅基础设施适配器使用的镜像仓库服务端点';
COMMENT ON COLUMN registry_connections.credential_ref IS '指向受管秘密或环境身份的不透明凭据引用';
COMMENT ON COLUMN registry_connections.availability IS '最近健康检查是否允许使用连接';
COMMENT ON COLUMN registry_connections.system_managed IS '是否由系统应用或环境自动维护连接';
COMMENT ON COLUMN registry_connections.created_at IS '连接记录创建时间';
COMMENT ON COLUMN registry_connections.created_by IS '创建连接的操作者标识';
COMMENT ON COLUMN registry_connections.updated_at IS '连接记录最近更新时间';
COMMENT ON COLUMN registry_connections.updated_by IS '最后更新连接的操作者标识';
COMMENT ON COLUMN registry_connections.deleted_at IS '软删除时间戳，零表示连接有效';
COMMENT ON COLUMN registry_connections.deleted_by IS '删除连接的操作者标识，零表示未删除';
COMMENT ON TABLE artifact_repositories IS '镜像产物仓库命名空间与发布策略表';
COMMENT ON COLUMN artifact_repositories.id IS '产物仓库内部主键';
COMMENT ON COLUMN artifact_repositories.connection_id IS '所属外部镜像仓库连接主键';
COMMENT ON COLUMN artifact_repositories.repository_ref IS '连接内可发布的镜像仓库稳定引用';
COMMENT ON COLUMN artifact_repositories.display_name IS '产物仓库管理界面展示名称';
COMMENT ON COLUMN artifact_repositories.allow_push IS '是否允许构建任务向该仓库发布产物';
COMMENT ON COLUMN artifact_repositories.created_at IS '产物仓库记录创建时间';
COMMENT ON COLUMN artifact_repositories.created_by IS '创建产物仓库的操作者标识';
COMMENT ON COLUMN artifact_repositories.updated_at IS '产物仓库记录最近更新时间';
COMMENT ON COLUMN artifact_repositories.updated_by IS '最后更新产物仓库的操作者标识';
COMMENT ON COLUMN artifact_repositories.deleted_at IS '软删除时间戳，零表示仓库有效';
COMMENT ON COLUMN artifact_repositories.deleted_by IS '删除产物仓库的操作者标识，零表示未删除';
COMMENT ON TABLE artifact_repository_user_assignments IS '产物仓库发布使用授权关系表';
COMMENT ON COLUMN artifact_repository_user_assignments.id IS '产物仓库授权内部主键';
COMMENT ON COLUMN artifact_repository_user_assignments.repository_id IS '被授权使用的产物仓库主键';
COMMENT ON COLUMN artifact_repository_user_assignments.user_id IS '获得发布使用权的用户标识';
COMMENT ON COLUMN artifact_repository_user_assignments.created_at IS '授权创建时间';
COMMENT ON COLUMN artifact_repository_user_assignments.created_by IS '创建授权的操作者标识';
COMMENT ON COLUMN artifact_repository_user_assignments.updated_at IS '授权最近更新时间';
COMMENT ON COLUMN artifact_repository_user_assignments.updated_by IS '最后更新授权的操作者标识';
COMMENT ON COLUMN artifact_repository_user_assignments.deleted_at IS '软删除时间戳，零表示授权有效';
COMMENT ON COLUMN artifact_repository_user_assignments.deleted_by IS '撤销授权的操作者标识，零表示未撤销';
