CREATE TABLE runtime_target_builder_telemetry_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runtime_target_id BIGINT NOT NULL REFERENCES runtime_targets(id) ON DELETE RESTRICT,
  agent_id VARCHAR(255) NOT NULL,
  telemetry_sequence BIGINT NOT NULL CHECK (telemetry_sequence > 0),
  builder_scope VARCHAR(255) NOT NULL,
  provider_id VARCHAR(128) NOT NULL,
  capability_profile VARCHAR(255) NOT NULL,
  capability_version VARCHAR(128) NOT NULL,
  affinity_key VARCHAR(255) NOT NULL DEFAULT '',
  available BOOLEAN NOT NULL,
  running_builds INTEGER NOT NULL CHECK (running_builds >= 0),
  queued_builds INTEGER NOT NULL CHECK (queued_builds >= 0),
  allocatable_slots INTEGER NOT NULL CHECK (allocatable_slots >= 0),
  observed_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  source_ref VARCHAR(255) NOT NULL,
  provenance VARCHAR(255) NOT NULL,
  integrity VARCHAR(255) NOT NULL,
  unsupported_dimensions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT runtime_target_builder_telemetry_window_check CHECK (expires_at > observed_at),
	CONSTRAINT uq_runtime_target_builder_telemetry_agent_sequence UNIQUE (runtime_target_id, agent_id, telemetry_sequence)
);

CREATE INDEX idx_runtime_target_builder_telemetry_latest
  ON runtime_target_builder_telemetry_observations (runtime_target_id, observed_at DESC, id DESC);

COMMENT ON TABLE runtime_target_builder_telemetry_observations IS '构建代理或控制平面上报的运行目标构建器遥测观察记录';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.id IS '遥测观察内部主键';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.runtime_target_id IS '关联的运行目标主键';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.agent_id IS '签名并提交该遥测报告的构建代理身份标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.telemetry_sequence IS '该构建代理已验签并接受的单调遥测序列';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.builder_scope IS '构建代理管理的构建器范围稳定标识，不是构建领域实例标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.provider_id IS '提供遥测的运行时提供方稳定标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.capability_profile IS '构建器当前能力配置档案标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.capability_version IS '构建器能力事实的版本标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.affinity_key IS '动态 affinity 策略匹配的构建器亲和稳定键';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.available IS '构建器健康且可接受新执行时为真';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.running_builds IS '该构建器范围内正在执行的构建数量';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.queued_builds IS '该构建器范围内等待执行的构建数量';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.allocatable_slots IS '当前可为新构建分配的执行槽位数量';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.observed_at IS '构建代理完成本次观测的时间';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.expires_at IS '本次观测不得再用于动态放置的过期时间';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.source_ref IS '控制平面中可追溯且不含连接秘密的观测来源引用';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.provenance IS '构建代理或控制平面产生该观测的来源说明';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.integrity IS '控制平面对观测完整性的可验证摘要';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.unsupported_dimensions_json IS '提供方明确不支持的遥测维度稳定标识数组';
COMMENT ON COLUMN runtime_target_builder_telemetry_observations.created_at IS '遥测记录写入控制平面的时间';
