CREATE TABLE runtime_target_builder_telemetry_agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runtime_target_id BIGINT NOT NULL REFERENCES runtime_targets(id) ON DELETE RESTRICT,
  agent_id VARCHAR(255) NOT NULL,
  public_key BYTEA NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_runtime_target_builder_telemetry_agents_target_agent UNIQUE (runtime_target_id, agent_id)
);

COMMENT ON TABLE runtime_target_builder_telemetry_agents IS '运行目标已绑定构建代理的遥测签名验证公钥表';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.id IS '构建代理验证身份内部主键';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.runtime_target_id IS '构建代理绑定的运行目标主键';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.agent_id IS '构建代理在控制平面的稳定身份标识';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.public_key IS '仅用于验证遥测报告签名的构建代理公钥';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.enabled IS '是否允许该构建代理继续提交遥测报告';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.created_at IS '构建代理验证身份创建时间';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.updated_at IS '构建代理验证身份最近更新时间';
