CREATE TABLE runtime_target_agent_delivery_grants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id BIGINT NOT NULL REFERENCES runtime_target_agent_generations(id) ON DELETE RESTRICT,
  grant_id VARCHAR(128) NOT NULL,
  token_verifier CHAR(64) NOT NULL,
  expected_automation_id VARCHAR(255) NOT NULL,
  docker_installation_ref VARCHAR(512) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(32) NOT NULL,
  handoff_id VARCHAR(128) NOT NULL DEFAULT '',
  handed_off_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_reason VARCHAR(512) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_runtime_target_agent_delivery_grants_grant_id UNIQUE (grant_id),
  CONSTRAINT runtime_target_agent_delivery_grants_grant_id_check CHECK (btrim(grant_id) <> ''),
  CONSTRAINT runtime_target_agent_delivery_grants_token_verifier_check CHECK (token_verifier ~ '^[0-9a-f]{64}$'),
  CONSTRAINT runtime_target_agent_delivery_grants_automation_check CHECK (btrim(expected_automation_id) <> ''),
  CONSTRAINT runtime_target_agent_delivery_grants_installation_check CHECK (btrim(docker_installation_ref) <> ''),
  CONSTRAINT runtime_target_agent_delivery_grants_status_check CHECK (status IN ('pending', 'delivered', 'consumed', 'revoked')),
  CONSTRAINT runtime_target_agent_delivery_grants_handoff_check CHECK (
    (handoff_id = '' AND handed_off_at IS NULL) OR (handoff_id <> '' AND handed_off_at IS NOT NULL)
  ),
  CONSTRAINT runtime_target_agent_delivery_grants_delivered_check CHECK (status NOT IN ('delivered', 'consumed') OR delivered_at IS NOT NULL),
  CONSTRAINT runtime_target_agent_delivery_grants_consumed_check CHECK (status <> 'consumed' OR consumed_at IS NOT NULL),
  CONSTRAINT runtime_target_agent_delivery_grants_revoked_check CHECK (status <> 'revoked' OR revoked_at IS NOT NULL)
);

-- 同一世代同一时刻只允许一个仍可消费的投递授权，保留已撤销授权供审计与重放拒绝使用。
CREATE UNIQUE INDEX uq_runtime_target_agent_delivery_grants_live_generation
  ON runtime_target_agent_delivery_grants (generation_id)
  WHERE status IN ('pending', 'delivered') AND deleted_at = 0;

-- handoff 标识由 Runtime Target 一次性签发，必须跨所有有效历史记录保持唯一。
CREATE UNIQUE INDEX uq_runtime_target_agent_delivery_grants_handoff
  ON runtime_target_agent_delivery_grants (handoff_id)
  WHERE handoff_id <> '' AND deleted_at = 0;

CREATE INDEX idx_runtime_target_agent_delivery_grants_pending_expiry
  ON runtime_target_agent_delivery_grants (status, expires_at)
  WHERE deleted_at = 0;

COMMENT ON TABLE runtime_target_agent_delivery_grants IS '运行目标代理引导材料投递授权表，保存不可逆令牌校验值与投递状态';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.id IS '代理投递授权内部主键';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.generation_id IS '关联的代理信任世代内部主键';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.grant_id IS '对外不透明且全局唯一的投递授权标识';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.token_verifier IS '引导令牌与服务端 pepper 组合后的 SHA-256 十六进制校验值，不保存令牌';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.expected_automation_id IS '获准领取并回执投递授权的既有部署自动化身份标识';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.docker_installation_ref IS '冻结的 Docker 安装位置不透明引用，运行目标不读取其具体部署配置';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.expires_at IS '投递授权和引导令牌最晚允许消费时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.status IS '投递授权状态，取值为 pending、delivered、consumed 或 revoked';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.handoff_id IS 'Runtime Target 一次性接受的引导材料交接标识，空值表示尚未交接';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.handed_off_at IS 'Runtime Target 向既有部署信任边界释放令牌的服务端时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.delivered_at IS '已验证 Docker 投递回执的服务端接受时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.consumed_at IS '引导令牌完成证书绑定后被消费的服务端时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.revoked_at IS '投递授权被拒绝或失效后撤销的服务端时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.revoked_reason IS '撤销投递授权的非秘密原因摘要';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.created_at IS '投递授权创建时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.created_by IS '创建投递授权的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.updated_at IS '投递授权最近更新时间';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.updated_by IS '最近更新投递授权的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.deleted_at IS '投递授权软删除时间戳，零表示保留有效审计记录';
COMMENT ON COLUMN runtime_target_agent_delivery_grants.deleted_by IS '执行投递授权软删除的操作人主键，零表示未删除';

CREATE TABLE runtime_target_agent_delivery_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_grant_id BIGINT NOT NULL REFERENCES runtime_target_agent_delivery_grants(id) ON DELETE RESTRICT,
  receipt_id VARCHAR(128) NOT NULL,
  protocol_version VARCHAR(64) NOT NULL,
  automation_id VARCHAR(255) NOT NULL,
  handoff_id VARCHAR(128) NOT NULL,
  asserted_delivered_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ NOT NULL,
  docker_installation_ref VARCHAR(512) NOT NULL,
  docker_secret_ref VARCHAR(512) NOT NULL,
  payload_fingerprint CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_runtime_target_agent_delivery_receipts_receipt_id UNIQUE (receipt_id),
  CONSTRAINT runtime_target_agent_delivery_receipts_receipt_id_check CHECK (btrim(receipt_id) <> ''),
  CONSTRAINT runtime_target_agent_delivery_receipts_protocol_check CHECK (protocol_version = 'graft.delivery-receipt.v1'),
  CONSTRAINT runtime_target_agent_delivery_receipts_automation_check CHECK (btrim(automation_id) <> ''),
  CONSTRAINT runtime_target_agent_delivery_receipts_handoff_check CHECK (btrim(handoff_id) <> ''),
  CONSTRAINT runtime_target_agent_delivery_receipts_installation_check CHECK (btrim(docker_installation_ref) <> ''),
  CONSTRAINT runtime_target_agent_delivery_receipts_secret_check CHECK (btrim(docker_secret_ref) <> ''),
  CONSTRAINT runtime_target_agent_delivery_receipts_fingerprint_check CHECK (payload_fingerprint ~ '^[0-9a-f]{64}$')
);

-- 每个投递授权只有一份可见回执；相同 receipt_id 的重试由内容摘要比对实现幂等。
CREATE UNIQUE INDEX uq_runtime_target_agent_delivery_receipts_live_grant
  ON runtime_target_agent_delivery_receipts (delivery_grant_id)
  WHERE deleted_at = 0;

CREATE INDEX idx_runtime_target_agent_delivery_receipts_handoff
  ON runtime_target_agent_delivery_receipts (handoff_id)
  WHERE deleted_at = 0;

COMMENT ON TABLE runtime_target_agent_delivery_receipts IS '运行目标代理 Docker 引导材料投递回执证据表，不作为代理激活依据';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.id IS '代理投递回执内部主键';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.delivery_grant_id IS '关联的代理投递授权内部主键';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.receipt_id IS '部署自动化生成且全局唯一的回执标识';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.protocol_version IS '回执信封协议版本，当前仅允许 graft.delivery-receipt.v1';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.automation_id IS '既有部署信任边界已验证的自动化身份标识';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.handoff_id IS '回执必须匹配的 Runtime Target 一次性交接标识';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.asserted_delivered_at IS '部署自动化声明 Docker 秘密材料已投递的时间，仅作证据';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.accepted_at IS 'Runtime Target 验证并保存回执的服务端时间';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.docker_installation_ref IS '回执中的 Docker 安装位置不透明引用，必须匹配投递授权';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.docker_secret_ref IS 'Docker 秘密材料的非秘密不透明引用，不保存秘密值';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.payload_fingerprint IS '回执规范化内容的 SHA-256 十六进制摘要，用于幂等重放核验';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.created_at IS '投递回执创建时间';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.created_by IS '创建投递回执的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.updated_at IS '投递回执最近更新时间';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.updated_by IS '最近更新投递回执的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.deleted_at IS '投递回执软删除时间戳，零表示保留有效审计证据';
COMMENT ON COLUMN runtime_target_agent_delivery_receipts.deleted_by IS '执行投递回执软删除的操作人主键，零表示未删除';
