CREATE TABLE runtime_target_agent_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runtime_target_id BIGINT NOT NULL REFERENCES runtime_targets(id) ON DELETE RESTRICT,
  identity_id VARCHAR(255) NOT NULL,
  agent_id VARCHAR(255) NOT NULL,
  provider_id VARCHAR(128) NOT NULL,
  builder_scope VARCHAR(255) NOT NULL,
  capability_profile VARCHAR(255) NOT NULL,
  capability_version VARCHAR(128) NOT NULL,
  image_digest VARCHAR(512) NOT NULL DEFAULT '',
  agent_version VARCHAR(128) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT runtime_target_agent_identities_identity_id_check CHECK (btrim(identity_id) <> ''),
  CONSTRAINT runtime_target_agent_identities_agent_id_check CHECK (btrim(agent_id) <> ''),
  CONSTRAINT runtime_target_agent_identities_provider_id_check CHECK (btrim(provider_id) <> ''),
  CONSTRAINT runtime_target_agent_identities_builder_scope_check CHECK (btrim(builder_scope) <> ''),
  CONSTRAINT runtime_target_agent_identities_capability_profile_check CHECK (btrim(capability_profile) <> ''),
  CONSTRAINT runtime_target_agent_identities_capability_version_check CHECK (btrim(capability_version) <> '')
);

CREATE UNIQUE INDEX uq_runtime_target_agent_identities_identity_live
  ON runtime_target_agent_identities (identity_id)
  WHERE deleted_at = 0;

CREATE UNIQUE INDEX uq_runtime_target_agent_identities_target_agent_live
  ON runtime_target_agent_identities (runtime_target_id, agent_id)
  WHERE deleted_at = 0;

COMMENT ON TABLE runtime_target_agent_identities IS '运行目标受 Vault 管理的代理稳定身份绑定表';
COMMENT ON COLUMN runtime_target_agent_identities.id IS '代理稳定身份内部主键';
COMMENT ON COLUMN runtime_target_agent_identities.runtime_target_id IS '代理绑定的运行目标主键';
COMMENT ON COLUMN runtime_target_agent_identities.identity_id IS 'Vault 返回且不含秘密材料的稳定机器身份引用';
COMMENT ON COLUMN runtime_target_agent_identities.agent_id IS '运行目标内稳定且跨世代不变的代理标识';
COMMENT ON COLUMN runtime_target_agent_identities.provider_id IS '代理受限绑定的运行时提供方稳定标识';
COMMENT ON COLUMN runtime_target_agent_identities.builder_scope IS '代理可操作的构建器范围稳定标识';
COMMENT ON COLUMN runtime_target_agent_identities.capability_profile IS '代理受限能力配置档案标识';
COMMENT ON COLUMN runtime_target_agent_identities.capability_version IS '代理能力配置档案的稳定版本标识';
COMMENT ON COLUMN runtime_target_agent_identities.image_digest IS '代理受控 OCI 镜像摘要，不含镜像仓库凭据';
COMMENT ON COLUMN runtime_target_agent_identities.agent_version IS '代理实现版本，用于诊断与兼容性核验';
COMMENT ON COLUMN runtime_target_agent_identities.created_at IS '稳定身份绑定创建时间';
COMMENT ON COLUMN runtime_target_agent_identities.created_by IS '创建稳定身份绑定的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_identities.updated_at IS '稳定身份绑定最近更新时间';
COMMENT ON COLUMN runtime_target_agent_identities.updated_by IS '最近更新稳定身份绑定的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_identities.deleted_at IS '稳定身份绑定软删除时间戳，零表示有效记录';
COMMENT ON COLUMN runtime_target_agent_identities.deleted_by IS '执行稳定身份绑定软删除的操作人主键，零表示未删除';

CREATE TABLE runtime_target_agent_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_id BIGINT NOT NULL REFERENCES runtime_target_agent_identities(id) ON DELETE RESTRICT,
  generation BIGINT NOT NULL,
  enrollment_ref VARCHAR(512) NOT NULL,
  trust_bundle_ref VARCHAR(512) NOT NULL,
  trust_bundle_version VARCHAR(255) NOT NULL,
  certificate_issuer VARCHAR(512) NOT NULL DEFAULT '',
  certificate_serial VARCHAR(512) NOT NULL DEFAULT '',
  public_key_fingerprint VARCHAR(512) NOT NULL DEFAULT '',
  expires_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(32) NOT NULL,
  activated_at TIMESTAMPTZ,
  retired_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_reason VARCHAR(512) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT NOT NULL DEFAULT 0,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_runtime_target_agent_generations_identity_generation UNIQUE (identity_id, generation),
  CONSTRAINT runtime_target_agent_generations_positive_generation_check CHECK (generation > 0),
  CONSTRAINT runtime_target_agent_generations_status_check CHECK (status IN ('pending', 'active', 'revoked', 'retired')),
  CONSTRAINT runtime_target_agent_generations_pending_metadata_check CHECK (
    status <> 'pending' OR (certificate_serial = '' AND public_key_fingerprint = '' AND activated_at IS NULL)
  ),
  CONSTRAINT runtime_target_agent_generations_active_metadata_check CHECK (
    status <> 'active' OR (certificate_issuer <> '' AND certificate_serial <> '' AND public_key_fingerprint <> '' AND activated_at IS NOT NULL AND revoked_at IS NULL AND retired_at IS NULL)
  ),
  CONSTRAINT runtime_target_agent_generations_revoked_timestamp_check CHECK (status <> 'revoked' OR revoked_at IS NOT NULL),
  CONSTRAINT runtime_target_agent_generations_retired_timestamp_check CHECK (status <> 'retired' OR retired_at IS NOT NULL)
);

CREATE UNIQUE INDEX uq_runtime_target_agent_generations_active_identity
  ON runtime_target_agent_generations (identity_id)
  WHERE status = 'active' AND deleted_at = 0;

CREATE INDEX idx_runtime_target_agent_generations_active_lookup
  ON runtime_target_agent_generations (identity_id, generation, expires_at)
  WHERE status = 'active' AND deleted_at = 0;

COMMENT ON TABLE runtime_target_agent_generations IS '运行目标代理受 Vault 管理的证书信任世代表';
COMMENT ON COLUMN runtime_target_agent_generations.id IS '代理证书信任世代内部主键';
COMMENT ON COLUMN runtime_target_agent_generations.identity_id IS '关联的代理稳定身份内部主键';
COMMENT ON COLUMN runtime_target_agent_generations.generation IS '代理稳定身份单调递增且不可复用的信任世代号';
COMMENT ON COLUMN runtime_target_agent_generations.enrollment_ref IS 'Vault 返回的不透明登记引用，不包含引导秘密';
COMMENT ON COLUMN runtime_target_agent_generations.trust_bundle_ref IS 'Vault 返回的不透明信任束引用，不包含证书 PEM';
COMMENT ON COLUMN runtime_target_agent_generations.trust_bundle_version IS '签发该世代时使用的信任束版本标识';
COMMENT ON COLUMN runtime_target_agent_generations.certificate_issuer IS '客户端证书签发者非秘密标识';
COMMENT ON COLUMN runtime_target_agent_generations.certificate_serial IS '客户端证书序列号，用于逐请求绑定核验';
COMMENT ON COLUMN runtime_target_agent_generations.public_key_fingerprint IS '客户端证书公钥指纹，不保存公钥或私钥材料';
COMMENT ON COLUMN runtime_target_agent_generations.expires_at IS '客户端证书和登记材料最晚允许使用的到期时间';
COMMENT ON COLUMN runtime_target_agent_generations.status IS '信任世代生命周期状态，只有 active 可进入后续 mTLS 核验';
COMMENT ON COLUMN runtime_target_agent_generations.activated_at IS '世代完成外部证书投递并开始受信任的时间';
COMMENT ON COLUMN runtime_target_agent_generations.retired_at IS '世代被新世代替代后永久退出受信任集合的时间';
COMMENT ON COLUMN runtime_target_agent_generations.revoked_at IS '世代被撤销后永久拒绝访问的时间';
COMMENT ON COLUMN runtime_target_agent_generations.revoked_reason IS '撤销或重置信任的非秘密原因摘要';
COMMENT ON COLUMN runtime_target_agent_generations.created_at IS '信任世代创建时间';
COMMENT ON COLUMN runtime_target_agent_generations.created_by IS '创建信任世代的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_generations.updated_at IS '信任世代最近更新时间';
COMMENT ON COLUMN runtime_target_agent_generations.updated_by IS '最近更新信任世代的操作人主键，系统操作为零';
COMMENT ON COLUMN runtime_target_agent_generations.deleted_at IS '信任世代软删除时间戳，零表示保留审计事实';
COMMENT ON COLUMN runtime_target_agent_generations.deleted_by IS '执行信任世代软删除的操作人主键，零表示未删除';

UPDATE runtime_target_builder_telemetry_agents
SET enabled = false
WHERE enabled = true;

COMMENT ON TABLE runtime_target_builder_telemetry_agents IS '历史 Ed25519 构建代理遥测绑定表，仅保留可读审计事实且不得用于信任或动态准入';
COMMENT ON COLUMN runtime_target_builder_telemetry_agents.enabled IS '历史遥测绑定启用标记，信任协议切换后固定为否且不得重新用于准入';
