// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "用户名，用于登录和唯一标识"},
		{Name: "display", Type: field.TypeString, Comment: "显示名称，用于后台展示"},
		{Name: "status", Type: field.TypeString, Comment: "状态：enabled 启用，disabled 禁用", Default: "enabled"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "created_by", Type: field.TypeUint64, Comment: "创建人用户 ID，0 表示系统", Default: 0},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "updated_by", Type: field.TypeUint64, Comment: "最后更新人用户 ID，0 表示系统", Default: 0},
		{Name: "deleted_at", Type: field.TypeInt64, Comment: "软删除时间戳，0 表示未删除", Default: 0},
		{Name: "deleted_by", Type: field.TypeUint64, Comment: "删除人用户 ID，0 表示未删除", Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Comment:    "用户基础信息表（用户模块）",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
