CREATE TABLE IF NOT EXISTS "roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying NOT NULL,
  "display" character varying NOT NULL,
  "description" character varying NULL,
  "builtin" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "roles_name_key" ON "roles" ("name");

CREATE TABLE IF NOT EXISTS "permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" character varying NOT NULL,
  "display" character varying NOT NULL,
  "description" character varying NULL,
  "category" character varying NOT NULL DEFAULT 'api',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_code_key" ON "permissions" ("code");

CREATE TABLE IF NOT EXISTS "user_roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz NOT NULL,
  "role_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_roles_roles_user_roles"
    FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_roles_users_user_roles"
    FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "userrole_user_id_role_id" ON "user_roles" ("user_id", "role_id");
CREATE INDEX IF NOT EXISTS "userrole_role_id" ON "user_roles" ("role_id");

CREATE TABLE IF NOT EXISTS "role_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz NOT NULL,
  "permission_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "role_permissions_permissions_role_permissions"
    FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "role_permissions_roles_role_permissions"
    FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
CREATE INDEX IF NOT EXISTS "rolepermission_permission_id" ON "role_permissions" ("permission_id");
