// Package healthopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package healthopenapi

// Defines values for GetHealthz200JSONResponseBodyStatus.
const (
	Ok GetHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealthz200JSONResponseBodyStatus enum.
func (e GetHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetHealthz200JSONResponseBodyStatus defines parameters for GetHealthz.
type GetHealthz200JSONResponseBodyStatus string
