export const API_CODE = {
  OK: 'OK',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_REFRESH_SESSION: 'AUTH_INVALID_REFRESH_SESSION',
  AUTH_MISSING_ACTOR: 'AUTH_MISSING_ACTOR',
  AUTH_MISSING_PERMISSION: 'AUTH_MISSING_PERMISSION',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_PASSWORD_POLICY_VIOLATION: 'AUTH_PASSWORD_POLICY_VIOLATION',
  AUTH_PASSWORD_REUSE_FORBIDDEN: 'AUTH_PASSWORD_REUSE_FORBIDDEN',
  AUTH_CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  COMMON_INVALID_ARGUMENT: 'COMMON_INVALID_ARGUMENT',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export type ApiCode = (typeof API_CODE)[keyof typeof API_CODE];

// 后端可能先于前端发布新增响应码；保留未知字符串，避免错误处理把合法响应误判为类型不匹配。
export type ApiResponseCode = string;
