type: object
required:
  - container_id
  - container_name
  - service_name
  - source
  - line
  - occurred_at
  - stream
properties:
  container_id:
    type: string
  container_name:
    type: string
  service_name:
    type: string
  source:
    $ref: ./application-log-entry-source.yaml
  line:
    type: string
  occurred_at:
    type: string
    format: date-time
  stream:
    $ref: ./application-log-entry-stream.yaml
