type: string
enum:
  - directory
  - compose
  - env
  - config
  - text
  - binary
  - unsupported
x-enum-varnames:
  - ApplicationWorkspaceFileKindDirectory
  - ApplicationWorkspaceFileKindCompose
  - ApplicationWorkspaceFileKindEnv
  - ApplicationWorkspaceFileKindConfig
  - ApplicationWorkspaceFileKindText
  - ApplicationWorkspaceFileKindBinary
  - ApplicationWorkspaceFileKindUnsupported
