type: object
required:
  - container_id
  - container_name
  - service_name
  - state
properties:
  container_id:
    type: string
  container_name:
    type: string
  service_name:
    type: string
  state:
    type: string
