type: object
required:
  - application_id
  - compose_project_name
  - entries
  - tail
  - timestamps
  - stdout
  - stderr
  - truncated
properties:
  application_id:
    $ref: ./application-id.yaml
  compose_project_name:
    type: string
  entries:
    type: array
    items:
      $ref: ./application-log-entry.yaml
  tail:
    type: integer
    minimum: 1
  since:
    type: string
    nullable: true
  timestamps:
    type: boolean
  stdout:
    type: boolean
  stderr:
    type: boolean
  truncated:
    type: boolean
