type: object
required: [traffic, errors_5xx, p95_latency]
properties:
  traffic:
    type: array
    maxItems: 5
    items:
      $ref: ./request-performance-route.yaml
  errors_5xx:
    type: array
    maxItems: 5
    items:
      $ref: ./request-performance-route.yaml
  p95_latency:
    type: array
    maxItems: 5
    items:
      $ref: ./request-performance-route.yaml
