import { ACCESS_LOG_ROUTE_PATH } from '@/modules/access-log/contract/paths';
import { AUDIT_ROUTE_PATH } from '@/modules/audit/contract/paths';
import { BUILD_ROUTE_PATH } from '@/modules/build/contract/paths';
import { MONITOR_ROUTE_PATH } from '@/modules/monitor/contract/paths';
import { NETWORK_ROUTE_PATH } from '@/modules/network/contract/paths';
import { SCHEDULED_TASK_ROUTE_PATH } from '@/modules/scheduled-task/contract/paths';

import { EVIDENCE_STATE, PRESENTATION_STATUS, projectWorkbenchScenario, type WorkbenchScenario } from './workbench';

/** 预览场景只服务 development-only 设计验收，删除预览路由时应整体移除。 */
export const DASHBOARD_PREVIEW_SCENARIO = {
  generatedAt: '2026-08-17T03:20:00.000Z',
  operational: {
    enabledModules: 22,
    failedTasks: 0,
    highRiskEvents: 0,
  },
  items: [
    {
      id: 'access-log-source',
      region: 'attention',
      status: PRESENTATION_STATUS.WARNING,
      evidenceState: EVIDENCE_STATE.SOURCE_FAILED,
      titleKey: 'dashboard.previewWorkbench.attention.accessLog.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.accessLog.description',
      actionable: true,
      action: { labelKey: 'dashboard.previewWorkbench.attention.accessLog.action', kind: 'retry' },
      sourceMetadata: { loadStatus: 'error', displayState: 'critical', priority: 'critical' },
    },
    {
      id: 'outbound-network',
      region: 'attention',
      status: PRESENTATION_STATUS.UNKNOWN,
      evidenceState: EVIDENCE_STATE.MISSING,
      titleKey: 'dashboard.previewWorkbench.attention.outbound.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.outbound.description',
      actionable: true,
      action: {
        labelKey: 'dashboard.previewWorkbench.attention.outbound.action',
        kind: 'navigate',
        route: NETWORK_ROUTE_PATH.OUTBOUND,
      },
      sourceMetadata: { loadStatus: 'normal', displayState: 'critical', priority: 'critical' },
    },
    {
      id: 'outbound-network-secondary',
      region: 'attention',
      status: PRESENTATION_STATUS.UNKNOWN,
      evidenceState: EVIDENCE_STATE.MISSING,
      titleKey: 'dashboard.previewWorkbench.attention.outbound.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.outbound.description',
    },
    {
      id: 'access-log-source-secondary',
      region: 'attention',
      status: PRESENTATION_STATUS.WARNING,
      evidenceState: EVIDENCE_STATE.SOURCE_FAILED,
      titleKey: 'dashboard.previewWorkbench.attention.accessLog.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.accessLog.description',
    },
    {
      id: 'outbound-network-tertiary',
      region: 'attention',
      status: PRESENTATION_STATUS.UNKNOWN,
      evidenceState: EVIDENCE_STATE.MISSING,
      titleKey: 'dashboard.previewWorkbench.attention.outbound.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.outbound.description',
    },
    {
      id: 'access-log-source-tertiary',
      region: 'attention',
      status: PRESENTATION_STATUS.WARNING,
      evidenceState: EVIDENCE_STATE.SOURCE_FAILED,
      titleKey: 'dashboard.previewWorkbench.attention.accessLog.title',
      descriptionKey: 'dashboard.previewWorkbench.attention.accessLog.description',
    },
    {
      id: 'health-postgresql',
      region: 'health',
      status: PRESENTATION_STATUS.HEALTHY,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.previewWorkbench.health.postgresql.title',
      descriptionKey: 'dashboard.previewWorkbench.health.postgresql.description',
    },
    {
      id: 'health-redis',
      region: 'health',
      status: PRESENTATION_STATUS.HEALTHY,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.previewWorkbench.health.redis.title',
      descriptionKey: 'dashboard.previewWorkbench.health.redis.description',
    },
    {
      id: 'health-postgresql-secondary',
      region: 'health',
      status: PRESENTATION_STATUS.HEALTHY,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.previewWorkbench.health.postgresql.title',
      descriptionKey: 'dashboard.previewWorkbench.health.postgresql.description',
    },
    {
      id: 'health-redis-secondary',
      region: 'health',
      status: PRESENTATION_STATUS.HEALTHY,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.previewWorkbench.health.redis.title',
      descriptionKey: 'dashboard.previewWorkbench.health.redis.description',
    },
    {
      id: 'health-postgresql-tertiary',
      region: 'health',
      status: PRESENTATION_STATUS.HEALTHY,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.previewWorkbench.health.postgresql.title',
      descriptionKey: 'dashboard.previewWorkbench.health.postgresql.description',
    },
    {
      id: 'resources-current',
      region: 'resources',
      status: PRESENTATION_STATUS.INFO,
      evidenceState: EVIDENCE_STATE.CONFIRMED,
      titleKey: 'dashboard.workbench.resources.sample.title',
      titleParams: { count: 8 },
      descriptionKey: 'dashboard.workbench.resources.sample.description',
      descriptionParams: { abnormal: 1, cpu: '14.6' },
      actionable: true,
      action: {
        labelKey: 'dashboard.actions.details',
        kind: 'navigate',
        route: MONITOR_ROUTE_PATH.OBSERVABILITY_OVERVIEW,
      },
    },
  ],
  moduleCoverage: {
    registeredModules: 24,
    enabledModules: 22,
    degradedModules: 1,
    normalContributionSources: 8,
    failedContributionSources: 1,
  },
  metricGroups: [
    {
      id: 'metric-group:scheduler:scheduler.task-attention',
      titleKey: 'dashboard.widget.schedulerTaskAttention.title',
      descriptionKey: 'dashboard.widget.schedulerTaskAttention.description',
      action: {
        kind: 'navigate',
        labelKey: 'dashboard.actions.details',
        route: SCHEDULED_TASK_ROUTE_PATH.LIST,
      },
      sourceWidgetId: 'scheduler.task-attention',
      metrics: [
        {
          key: 'failed',
          labelKey: 'dashboard.widget.schedulerTaskAttention.failed',
          value: '0',
          descriptionKey: 'dashboard.widget.schedulerTaskAttention.failedDescription',
          tone: 'normal',
          route: SCHEDULED_TASK_ROUTE_PATH.LIST,
        },
        {
          key: 'running',
          labelKey: 'dashboard.widget.schedulerTaskAttention.running',
          value: '2',
          descriptionKey: 'dashboard.widget.schedulerTaskAttention.runningDescription',
          tone: 'info',
          route: SCHEDULED_TASK_ROUTE_PATH.LIST,
        },
        {
          key: 'disabled',
          labelKey: 'dashboard.widget.schedulerTaskAttention.disabled',
          value: '3',
          descriptionKey: 'dashboard.widget.schedulerTaskAttention.disabledDescription',
          tone: 'info',
          route: SCHEDULED_TASK_ROUTE_PATH.LIST,
        },
      ],
    },
  ],
  contextLinkGroups: [
    {
      id: 'context-link-group:preview:operations',
      titleKey: 'dashboard.workbench.quickActions.title',
      descriptionKey: 'dashboard.workbench.quickActions.description',
      sourceWidgetId: 'preview.operations',
      links: [
        {
          key: 'build-jobs',
          labelKey: 'dashboard.previewWorkbench.quickActions.createBuild.title',
          route: BUILD_ROUTE_PATH.JOBS,
          iconKey: 'build',
          disabled: false,
        },
        {
          key: 'observability',
          labelKey: 'dashboard.previewWorkbench.quickActions.observability.title',
          route: MONITOR_ROUTE_PATH.OBSERVABILITY_OVERVIEW,
          iconKey: 'observability-overview',
          disabled: false,
        },
        {
          key: 'audit',
          labelKey: 'dashboard.previewWorkbench.quickActions.audit.title',
          route: AUDIT_ROUTE_PATH.LOGS,
          iconKey: 'audit-trail',
          disabled: false,
        },
        {
          key: 'artifacts',
          labelKey: 'dashboard.previewWorkbench.quickActions.artifacts.title',
          route: BUILD_ROUTE_PATH.ARTIFACTS,
          iconKey: 'image-artifact',
          disabled: false,
        },
        {
          key: 'scheduled-tasks',
          labelKey: 'dashboard.previewWorkbench.quickActions.scheduledTasks.title',
          route: SCHEDULED_TASK_ROUTE_PATH.LIST,
          iconKey: 'scheduled-automation',
          disabled: false,
        },
        {
          key: 'access-logs',
          labelKey: 'dashboard.previewWorkbench.quickActions.accessLogs.title',
          route: ACCESS_LOG_ROUTE_PATH.LIST,
          iconKey: 'access-log',
          disabled: false,
        },
        {
          key: 'network-outbound',
          labelKey: 'dashboard.previewWorkbench.attention.outbound.title',
          route: NETWORK_ROUTE_PATH.OUTBOUND,
          disabled: false,
        },
        {
          key: 'build-create',
          labelKey: 'dashboard.previewWorkbench.quickActions.createBuild.title',
          route: BUILD_ROUTE_PATH.CREATE,
          disabled: false,
        },
      ],
    },
  ],
  resourceSummary: {
    state: 'loaded',
    route: MONITOR_ROUTE_PATH.OBSERVABILITY_OVERVIEW,
    overview: {
      abnormalContainers: 1,
      collectedAt: '2026-08-17T03:18:00.000Z',
      cpuTotalPercent: 14.6,
      memoryTotalLimitBytes: 8_589_934_592,
      memoryTotalPercent: 42.1,
      memoryTotalUsageBytes: 3_616_776_192,
      runningContainers: 8,
    },
    topCpu: [
      {
        id: 'api',
        name: 'graft-api',
        shortId: '0a1b2c3d',
        image: 'graft/api:latest',
        state: 'running',
        health: 'healthy',
        restartCount: 0,
        cpuPercent: 8.2,
        memoryPercent: 31.4,
        memoryUsageBytes: 674_309_120,
        memoryLimitBytes: 2_147_483_648,
        collectedAt: '2026-08-17T03:18:00.000Z',
      },
    ],
    topMemory: [
      {
        id: 'postgres',
        name: 'graft-postgres',
        shortId: '9f8e7d6c',
        image: 'postgres:17',
        state: 'running',
        health: 'healthy',
        restartCount: 0,
        cpuPercent: 2.3,
        memoryPercent: 48.6,
        memoryUsageBytes: 1_043_652_608,
        memoryLimitBytes: 2_147_483_648,
        collectedAt: '2026-08-17T03:18:00.000Z',
      },
    ],
    anomalies: [
      {
        id: 'worker',
        name: 'graft-worker',
        shortId: '4d5e6f7a',
        image: 'graft/worker:latest',
        state: 'restarting',
        health: 'unhealthy',
        restartCount: 4,
        cpuPercent: 1.7,
        memoryPercent: 12.8,
        memoryUsageBytes: 274_877_906,
        memoryLimitBytes: 2_147_483_648,
        collectedAt: '2026-08-17T03:18:00.000Z',
        status: 'Restarting (4)',
        reasonCode: 'state.restarting',
        reasonLabel: null,
      },
    ],
  },
  quickActions: [
    {
      id: 'create-build',
      iconKey: 'build',
      kind: 'action',
      titleKey: 'dashboard.previewWorkbench.quickActions.createBuild.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.createBuild.description',
      route: BUILD_ROUTE_PATH.CREATE,
      showOnHome: true,
    },
    {
      id: 'observability',
      iconKey: 'observability-overview',
      kind: 'navigation',
      titleKey: 'dashboard.previewWorkbench.quickActions.observability.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.observability.description',
      route: MONITOR_ROUTE_PATH.OBSERVABILITY_OVERVIEW,
      showOnHome: true,
    },
    {
      id: 'audit-logs',
      iconKey: 'audit-trail',
      kind: 'navigation',
      titleKey: 'dashboard.previewWorkbench.quickActions.audit.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.audit.description',
      route: AUDIT_ROUTE_PATH.LOGS,
      showOnHome: true,
    },
    {
      id: 'artifacts',
      iconKey: 'image-artifact',
      kind: 'navigation',
      titleKey: 'dashboard.previewWorkbench.quickActions.artifacts.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.artifacts.description',
      route: BUILD_ROUTE_PATH.ARTIFACTS,
      showOnHome: true,
    },
    {
      id: 'scheduled-tasks',
      iconKey: 'scheduled-automation',
      kind: 'navigation',
      titleKey: 'dashboard.previewWorkbench.quickActions.scheduledTasks.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.scheduledTasks.description',
      route: SCHEDULED_TASK_ROUTE_PATH.LIST,
      showOnHome: false,
    },
    {
      id: 'access-logs',
      iconKey: 'access-log',
      kind: 'navigation',
      titleKey: 'dashboard.previewWorkbench.quickActions.accessLogs.title',
      descriptionKey: 'dashboard.previewWorkbench.quickActions.accessLogs.description',
      route: ACCESS_LOG_ROUTE_PATH.LIST,
      showOnHome: false,
    },
  ],
} as const satisfies WorkbenchScenario;

export const DASHBOARD_PREVIEW_PRESENTATION = projectWorkbenchScenario(DASHBOARD_PREVIEW_SCENARIO);
