// Package auditopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package auditopenapi

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetAuditLogs400JSONResponseBodySuccess.
const (
	GetAuditLogs400JSONResponseBodySuccessFalse GetAuditLogs400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAuditLogs400JSONResponseBodySuccess enum.
func (e GetAuditLogs400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAuditLogs400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAuditLogs401JSONResponseBodySuccess.
const (
	GetAuditLogs401JSONResponseBodySuccessFalse GetAuditLogs401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAuditLogs401JSONResponseBodySuccess enum.
func (e GetAuditLogs401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAuditLogs401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAuditLogs403JSONResponseBodySuccess.
const (
	GetAuditLogs403JSONResponseBodySuccessFalse GetAuditLogs403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAuditLogs403JSONResponseBodySuccess enum.
func (e GetAuditLogs403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAuditLogs403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAuditLogs500JSONResponseBodySuccess.
const (
	GetAuditLogs500JSONResponseBodySuccessFalse GetAuditLogs500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAuditLogs500JSONResponseBodySuccess enum.
func (e GetAuditLogs500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAuditLogs500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	Page         *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize     *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
	ActorUserId  *int64     `form:"actor_user_id,omitempty" json:"actor_user_id,omitempty"`
	Action       *string    `form:"action,omitempty" json:"action,omitempty"`
	ResourceType *string    `form:"resource_type,omitempty" json:"resource_type,omitempty"`
	ResourceId   *string    `form:"resource_id,omitempty" json:"resource_id,omitempty"`
	ResourceName *string    `form:"resource_name,omitempty" json:"resource_name,omitempty"`
	RequestId    *string    `form:"request_id,omitempty" json:"request_id,omitempty"`
	Success      *bool      `form:"success,omitempty" json:"success,omitempty"`
	CreatedFrom  *time.Time `form:"created_from,omitempty" json:"created_from,omitempty"`
	CreatedTo    *time.Time `form:"created_to,omitempty" json:"created_to,omitempty"`

	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAuditLogs400JSONResponseBodySuccess defines parameters for GetAuditLogs.
type GetAuditLogs400JSONResponseBodySuccess bool

// GetAuditLogs401JSONResponseBodySuccess defines parameters for GetAuditLogs.
type GetAuditLogs401JSONResponseBodySuccess bool

// GetAuditLogs403JSONResponseBodySuccess defines parameters for GetAuditLogs.
type GetAuditLogs403JSONResponseBodySuccess bool

// GetAuditLogs500JSONResponseBodySuccess defines parameters for GetAuditLogs.
type GetAuditLogs500JSONResponseBodySuccess bool
