CREATE TABLE backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purpose VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
  config_snapshot_ref TEXT NOT NULL,
  config_snapshot_sha256 CHAR(64) NOT NULL,
  config_snapshot_bytes BIGINT NOT NULL,
  database_dump_ref TEXT NOT NULL,
  database_dump_sha256 CHAR(64) NOT NULL,
  database_dump_bytes BIGINT NOT NULL,
  retain_until TIMESTAMPTZ NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  restore_code VARCHAR(128) NOT NULL DEFAULT '',
  restore_at TIMESTAMPTZ NULL,
  deleted_at BIGINT NOT NULL DEFAULT 0,
  deleted_by BIGINT NULL,
  CONSTRAINT backups_status_check CHECK (status IN ('AVAILABLE', 'EXPIRED', 'RESTORED')),
  CONSTRAINT backups_config_snapshot_bytes_check CHECK (config_snapshot_bytes >= 0),
  CONSTRAINT backups_database_dump_bytes_check CHECK (database_dump_bytes >= 0)
);

CREATE INDEX idx_backups_retain_until_live ON backups (retain_until ASC, id ASC) WHERE deleted_at = 0;
CREATE INDEX idx_backups_purpose_created_live ON backups (purpose, created_at DESC, id DESC) WHERE deleted_at = 0;

COMMENT ON TABLE backups IS '平台备份工件元数据与恢复证据表';
COMMENT ON COLUMN backups.id IS '备份记录主键';
COMMENT ON COLUMN backups.purpose IS '备份用途稳定标识，例如平台更新前备份';
COMMENT ON COLUMN backups.status IS '备份保留状态，取值为 AVAILABLE、EXPIRED、RESTORED';
COMMENT ON COLUMN backups.config_snapshot_ref IS '受控存储中的配置快照引用，不保存配置正文';
COMMENT ON COLUMN backups.config_snapshot_sha256 IS '配置快照工件的 SHA-256 完整性校验值';
COMMENT ON COLUMN backups.config_snapshot_bytes IS '配置快照工件大小，单位字节';
COMMENT ON COLUMN backups.database_dump_ref IS '受控存储中的 PostgreSQL dump 引用，不保存 dump 正文';
COMMENT ON COLUMN backups.database_dump_sha256 IS 'PostgreSQL dump 工件的 SHA-256 完整性校验值';
COMMENT ON COLUMN backups.database_dump_bytes IS 'PostgreSQL dump 工件大小，单位字节';
COMMENT ON COLUMN backups.retain_until IS '备份保留截止时间，到期后不再作为恢复依据';
COMMENT ON COLUMN backups.created_by IS '创建备份请求的管理员用户标识，自动流程可为空';
COMMENT ON COLUMN backups.created_at IS '备份元数据记录创建时间';
COMMENT ON COLUMN backups.updated_at IS '备份元数据最近更新时间';
COMMENT ON COLUMN backups.restore_code IS '恢复结果稳定代码，不包含配置或数据库内容';
COMMENT ON COLUMN backups.restore_at IS '最近一次记录恢复结果的时间，为空表示尚未记录';
COMMENT ON COLUMN backups.deleted_at IS '备份元数据软删除时间戳，零表示有效记录';
COMMENT ON COLUMN backups.deleted_by IS '执行软删除的管理员用户标识，为空表示未删除';
