export default {
  showFooter: true,
  isSidebarCompact: false,
  showBreadcrumb: false,
  menuAutoCollapsed: false,
  menuAlwaysExpanded: false,
  mode: 'dark',
  layout: 'mix',
  splitMenu: true,
  sideMode: 'dark',
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: true,
  showHeader: true,
  showThemeWorkbenchDock: true,
  isAcrylicEnabled: true,
  preserveThemePersonalization: true,
  brandTheme: '#61AFEF',
};
