import type {
  ThemeModeTokenState,
  ThemePresetDefinition,
  ThemeTokenDefinition,
  ThemeWorkbenchAuthorityPatch,
  ThemeWorkbenchGroupDefinition,
  ThemeWorkbenchScenarioPresetDefinition,
  ThemeWorkbenchStylePatch,
} from '@/types/theme';

export const DEFAULT_THEME_PRESET_ID = 'one-dark-pro';

export const GRAFT_BASE_THEME_TOKENS: ThemeModeTokenState = {
  light: {
    '--td-bg-color-page': '#fafbfc',
    '--td-bg-color-container': '#ffffff',
    '--td-bg-color-container-hover': '#f5f7fa',
    '--td-bg-color-secondarycontainer': '#f7f9fb',
    '--td-bg-color-component': '#f3f6f9',
    '--td-text-color-primary': '#111827',
    '--td-text-color-secondary': '#4b5563',
    '--td-text-color-placeholder': '#8a94a6',
    '--td-text-color-disabled': '#b8c0cc',
    '--td-component-border': '#d9e0ea',
    '--td-component-stroke': '#e5eaf2',
    '--td-border-level-1-color': '#e8edf4',
    '--td-scrollbar-color': '#c7d0dc',
    '--graft-scrollbar-track-color': '#edf1f6',
    '--graft-scrollbar-thumb-hover-color': '#aeb9c7',
    '--graft-shell-bg': '#fafbfc',
    '--graft-shell-header-bg': '#ffffff',
    '--graft-shell-sidebar-bg': '#ffffff',
    '--graft-shell-content-bg': '#fafbfc',
    '--graft-shell-border-color': '#e5eaf2',
    '--graft-card-bg': '#ffffff',
    '--graft-card-bg-hover': '#f7f9fc',
    '--graft-card-border-color': '#e5eaf2',
    '--graft-card-elevated-bg': '#ffffff',
    '--graft-glass-ambient-color': 'color-mix(in srgb, var(--td-brand-color) 7%, transparent)',
    '--graft-glass-bg': 'rgba(255, 255, 255, 0.54)',
    '--graft-glass-border': 'rgba(255, 255, 255, 0.08)',
    '--graft-glass-shadow': '0 10px 28px rgba(15, 23, 42, 0.06)',
    '--graft-glass-blur': '28px',
    '--graft-glass-highlight': 'rgba(255, 255, 255, 0.12)',
    '--graft-glass-content-bg': 'rgba(255, 255, 255, 0.72)',
    '--graft-glass-content-border': 'rgba(255, 255, 255, 0.12)',
    '--graft-glass-content-shadow': '0 6px 18px rgba(15, 23, 42, 0.05)',
    '--graft-glass-content-blur': '22px',
    '--graft-glass-noise-opacity': '0.015',
    '--graft-metric-value-color': 'var(--td-brand-color)',
    '--graft-chart-text-color': '#111827',
    '--graft-chart-placeholder-color': '#8a94a6',
    '--graft-chart-border-color': '#d9e0ea',
    '--graft-chart-container-color': '#ffffff',
    '--graft-monitor-cpu-color': '#2f6bff',
    '--graft-monitor-memory-color': '#168f6d',
    '--graft-monitor-load-color': '#c26a05',
    '--graft-monitor-runtime-alloc-color': '#6d5bd0',
    '--graft-monitor-runtime-heap-color': '#1f7fc9',
    '--graft-monitor-runtime-sys-color': '#a86a28',
    '--graft-monitor-goroutines-color': '#c73f80',
  },
  dark: {
    '--td-bg-color-page': '#0b1118',
    '--td-bg-color-container': '#151b24',
    '--td-bg-color-container-hover': '#1d2632',
    '--td-bg-color-secondarycontainer': '#121923',
    '--td-bg-color-component': '#1d2632',
    '--td-text-color-primary': '#f0f3f8',
    '--td-text-color-secondary': '#aeb8c7',
    '--td-text-color-placeholder': '#778397',
    '--td-text-color-disabled': '#5f6b7c',
    '--td-component-border': '#303b49',
    '--td-component-stroke': '#273241',
    '--td-border-level-1-color': '#273241',
    '--td-scrollbar-color': '#3a4655',
    '--graft-scrollbar-track-color': '#101720',
    '--graft-scrollbar-thumb-hover-color': '#526171',
    '--graft-dark-sidebar-bg': '#0f1720',
    '--graft-dark-header-bg': '#151b24',
    '--graft-dark-page-bg': '#0b1118',
    '--graft-dark-card-bg': '#151b24',
    '--graft-dark-card-elevated-bg': '#171f2a',
    '--graft-dark-border-color': '#273241',
    '--graft-dark-header-button-hover-bg': 'rgba(255,255,255,0.06)',
    '--graft-dark-header-button-active-bg': 'color-mix(in srgb, var(--td-brand-color) 18%, transparent)',
    '--graft-shell-bg': 'var(--graft-dark-page-bg)',
    '--graft-shell-header-bg': 'var(--graft-dark-header-bg)',
    '--graft-shell-sidebar-bg': 'var(--graft-dark-sidebar-bg)',
    '--graft-shell-content-bg': 'var(--graft-dark-page-bg)',
    '--graft-shell-border-color': 'var(--graft-dark-border-color)',
    '--graft-card-bg': 'var(--graft-dark-card-bg)',
    '--graft-card-bg-hover': '#1d2632',
    '--graft-card-border-color': 'var(--graft-dark-border-color)',
    '--graft-card-elevated-bg': 'var(--graft-dark-card-elevated-bg)',
    '--graft-glass-ambient-color': 'color-mix(in srgb, var(--td-brand-color) 9%, transparent)',
    '--graft-glass-bg': 'rgba(15, 20, 27, 0.58)',
    '--graft-glass-border': 'rgba(255, 255, 255, 0.08)',
    '--graft-glass-shadow': '0 12px 30px rgba(0, 0, 0, 0.18)',
    '--graft-glass-blur': '28px',
    '--graft-glass-highlight': 'rgba(255, 255, 255, 0.1)',
    '--graft-glass-content-bg': 'rgba(24, 31, 41, 0.72)',
    '--graft-glass-content-border': 'rgba(255, 255, 255, 0.1)',
    '--graft-glass-content-shadow': '0 6px 18px rgba(0, 0, 0, 0.16)',
    '--graft-glass-content-blur': '22px',
    '--graft-glass-noise-opacity': '0.015',
    '--graft-metric-value-color': 'var(--td-brand-color-6)',
    '--graft-chart-text-color': '#f0f3f8',
    '--graft-chart-placeholder-color': '#778397',
    '--graft-chart-border-color': '#303946',
    '--graft-chart-container-color': '#161b22',
    '--graft-monitor-cpu-color': '#7aa2ff',
    '--graft-monitor-memory-color': '#4fd1a5',
    '--graft-monitor-load-color': '#ffb347',
    '--graft-monitor-runtime-alloc-color': '#a78bfa',
    '--graft-monitor-runtime-heap-color': '#5ab0ff',
    '--graft-monitor-runtime-sys-color': '#f2a65a',
    '--graft-monitor-goroutines-color': '#ff70c4',
  },
};

export const THEME_WORKBENCH_GROUPS: ThemeWorkbenchGroupDefinition[] = [
  { key: 'overview', labelKey: 'layout.setting.workbench.groups.overview' },
  { key: 'presets', labelKey: 'layout.setting.workbench.groups.presets' },
  { key: 'appearance', labelKey: 'layout.setting.workbench.groups.appearance' },
  { key: 'layout', labelKey: 'layout.setting.workbench.groups.layout' },
  { key: 'typography', labelKey: 'layout.setting.workbench.groups.typography' },
  { key: 'style', labelKey: 'layout.setting.workbench.groups.style' },
  { key: 'advanced', labelKey: 'layout.setting.workbench.groups.advanced' },
];

export const THEME_TOKEN_DEFINITIONS: ThemeTokenDefinition[] = [
  {
    key: '--td-brand-color',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.primaryBrand',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-1',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale1',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-2',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale2',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-3',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale3',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-4',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale4',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-5',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale5',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-6',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale6',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-7',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale7',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-8',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale8',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-9',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale9',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-10',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale10',
    followsBrandColor: true,
  },
  { key: '--td-text-color-primary', group: 'text', labelKey: 'layout.setting.workbench.tokenDefinitions.primaryText' },
  {
    key: '--td-text-color-secondary',
    group: 'text',
    labelKey: 'layout.setting.workbench.tokenDefinitions.secondaryText',
  },
  {
    key: '--td-text-color-placeholder',
    group: 'text',
    labelKey: 'layout.setting.workbench.tokenDefinitions.placeholderText',
  },
  {
    key: '--td-bg-color-page',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.pageBackground',
  },
  {
    key: '--td-bg-color-container',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.containerBackground',
  },
  {
    key: '--td-bg-color-container-hover',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.containerHoverBackground',
  },
  {
    key: '--td-bg-color-secondarycontainer',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.secondaryContainerBackground',
  },
  {
    key: '--td-bg-color-component',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentBackground',
  },
  {
    key: '--graft-shell-bg',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.shellBackground',
  },
  {
    key: '--graft-shell-header-bg',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.shellHeaderBackground',
  },
  {
    key: '--graft-shell-sidebar-bg',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.shellSidebarBackground',
  },
  {
    key: '--graft-shell-content-bg',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.shellContentBackground',
  },
  { key: '--graft-card-bg', group: 'background', labelKey: 'layout.setting.workbench.tokenDefinitions.cardBackground' },
  {
    key: '--graft-card-bg-hover',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.cardHoverBackground',
  },
  {
    key: '--td-component-border',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentBorder',
  },
  {
    key: '--td-component-stroke',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentStroke',
  },
  {
    key: '--td-border-level-1-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.level1Border',
  },
  { key: '--td-scrollbar-color', group: 'border', labelKey: 'layout.setting.workbench.tokenDefinitions.scrollbar' },
  {
    key: '--graft-scrollbar-track-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.scrollbarTrack',
  },
  {
    key: '--graft-scrollbar-thumb-hover-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.scrollbarThumbHover',
  },
  {
    key: '--graft-shell-border-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.shellBorder',
  },
  {
    key: '--graft-card-border-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.cardBorder',
  },
  {
    key: '--graft-chart-text-color',
    group: 'chart',
    labelKey: 'layout.setting.workbench.tokenDefinitions.chartText',
  },
  {
    key: '--graft-chart-placeholder-color',
    group: 'chart',
    labelKey: 'layout.setting.workbench.tokenDefinitions.chartPlaceholder',
  },
  {
    key: '--graft-chart-border-color',
    group: 'chart',
    labelKey: 'layout.setting.workbench.tokenDefinitions.chartBorder',
  },
  {
    key: '--graft-chart-container-color',
    group: 'chart',
    labelKey: 'layout.setting.workbench.tokenDefinitions.chartContainer',
  },
  {
    key: '--td-success-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.successFeedback',
  },
  {
    key: '--td-error-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.errorFeedback',
  },
  {
    key: '--td-warning-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.warningFeedback',
  },
  { key: '--td-font-family', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.fontFamily' },
  {
    key: '--td-font-body-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.bodyMedium',
  },
  {
    key: '--td-font-title-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.titleMedium',
  },
  {
    key: '--td-font-title-large',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.titleLarge',
  },
  { key: '--td-radius-small', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.smallRadius' },
  {
    key: '--td-radius-default',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.defaultRadius',
  },
  {
    key: '--td-radius-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.mediumRadius',
  },
  { key: '--td-radius-large', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.largeRadius' },
  {
    key: '--td-radius-extraLarge',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.extraLargeRadius',
  },
  {
    key: '--td-radius-circle',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.circleRadius',
  },
  { key: '--td-shadow-1', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel1' },
  { key: '--td-shadow-2', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel2' },
  { key: '--td-shadow-3', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel3' },
  { key: '--graft-neo-accent', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.accentColor' },
  { key: '--graft-neo-ink', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.inkColor' },
  {
    key: '--graft-neo-surface',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.surfaceColor',
  },
  {
    key: '--graft-neo-muted-surface',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.mutedSurfaceColor',
  },
  { key: '--graft-neo-shadow', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.hardShadow' },
  {
    key: '--td-comp-size-xs',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeXs',
  },
  {
    key: '--td-comp-size-s',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeS',
  },
  {
    key: '--td-comp-size-m',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeM',
  },
  {
    key: '--td-comp-size-l',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeL',
  },
  {
    key: '--td-comp-size-xl',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeXl',
  },
  {
    key: '--graft-glass-ambient-color',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassAmbient',
  },
  { key: '--graft-glass-bg', group: 'material', labelKey: 'layout.setting.workbench.tokenDefinitions.glassBackground' },
  { key: '--graft-glass-border', group: 'material', labelKey: 'layout.setting.workbench.tokenDefinitions.glassBorder' },
  { key: '--graft-glass-shadow', group: 'material', labelKey: 'layout.setting.workbench.tokenDefinitions.glassShadow' },
  { key: '--graft-glass-blur', group: 'material', labelKey: 'layout.setting.workbench.tokenDefinitions.glassBlur' },
  {
    key: '--graft-glass-highlight',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassHighlight',
  },
  {
    key: '--graft-glass-content-bg',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassContentBackground',
  },
  {
    key: '--graft-glass-content-border',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassContentBorder',
  },
  {
    key: '--graft-glass-content-shadow',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassContentShadow',
  },
  {
    key: '--graft-glass-content-blur',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassContentBlur',
  },
  {
    key: '--graft-glass-noise-opacity',
    group: 'material',
    labelKey: 'layout.setting.workbench.tokenDefinitions.glassNoiseOpacity',
  },
];

const SIDE_LAYOUT_STYLE_PATCH: ThemeWorkbenchStylePatch = {
  layout: 'side',
  splitMenu: false,
  isSidebarFixed: true,
  isUseTabsRouter: false,
  showFooter: true,
  showHeader: true,
  showBreadcrumb: false,
  menuAutoCollapsed: false,
};

const MIX_LAYOUT_STYLE_PATCH: ThemeWorkbenchStylePatch = {
  layout: 'mix',
  splitMenu: true,
  isSidebarFixed: true,
  isUseTabsRouter: true,
  showFooter: true,
  showHeader: true,
  showBreadcrumb: false,
  menuAutoCollapsed: false,
};

const STANDARD_SYSTEM_AUTHORITY_PATCH: ThemeWorkbenchAuthorityPatch = {
  fontFamilyPreset: 'system',
  fontSizePreset: 'standard',
  radiusPreset: 'standard',
  shadowPreset: 'standard',
  densityPreset: 'standard',
};

const SOURCE_HAN_ROUNDED_AUTHORITY_PATCH: ThemeWorkbenchAuthorityPatch = {
  fontFamilyPreset: 'source-han-sans',
  fontSizePreset: 'standard',
  radiusPreset: 'rounded',
  shadowPreset: 'standard',
  densityPreset: 'comfortable',
};

function createDarkPalette(page: string, container: string, sidebar: string, border: string, hover: string) {
  return {
    dark: {
      '--td-bg-color-page': page,
      '--td-bg-color-container': container,
      '--td-bg-color-container-hover': hover,
      '--td-bg-color-secondarycontainer': sidebar,
      '--td-bg-color-component': hover,
      '--td-text-color-primary': '#E6EAF0',
      '--td-text-color-secondary': '#ABB2BF',
      '--td-text-color-placeholder': '#7F8796',
      '--td-component-border': border,
      '--td-component-stroke': border,
      '--td-border-level-1-color': border,
      '--td-scrollbar-color': border,
      '--graft-scrollbar-track-color': sidebar,
      '--graft-scrollbar-thumb-hover-color': '#5C6370',
      '--graft-shell-bg': page,
      '--graft-shell-header-bg': container,
      '--graft-shell-sidebar-bg': sidebar,
      '--graft-shell-content-bg': page,
      '--graft-shell-border-color': border,
      '--graft-card-bg': container,
      '--graft-card-bg-hover': hover,
      '--graft-card-border-color': border,
      '--graft-chart-text-color': '#E6EAF0',
      '--graft-chart-placeholder-color': '#7F8796',
      '--graft-chart-border-color': border,
      '--graft-chart-container-color': container,
    },
  } satisfies Partial<ThemeModeTokenState>;
}

function createAcrylicMaterial(surface: string, contentSurface: string, shadow: string) {
  return {
    dark: {
      '--graft-glass-ambient-color': 'color-mix(in srgb, var(--td-brand-color) 10%, transparent)',
      '--graft-glass-bg': surface,
      '--graft-glass-border': 'rgba(255, 255, 255, 0.1)',
      '--graft-glass-shadow': shadow,
      '--graft-glass-blur': '30px',
      '--graft-glass-content-bg': contentSurface,
      '--graft-glass-content-border': 'rgba(255, 255, 255, 0.12)',
      '--graft-glass-content-shadow': shadow,
      '--graft-glass-content-blur': '24px',
    },
  } satisfies Partial<ThemeModeTokenState>;
}

// 内置预设保持为纯前端本地配置，先服务当前工作台预览，不与后端契约耦合。
export const THEME_PRESET_DEFINITIONS: ThemePresetDefinition[] = [
  {
    id: 'industrial-yellow',
    labelKey: 'layout.setting.workbench.presets.industrialYellow.label',
    descriptionKey: 'layout.setting.workbench.presets.industrialYellow.description',
    category: 'operations',
    featured: true,
    brandTheme: '#B28A00',
    mode: 'light',
    tokenOverrides: {
      light: {
        '--td-bg-color-page': '#E8E8E5',
        '--td-bg-color-container': '#FFFEF8',
        '--td-bg-color-container-hover': '#F2F1EA',
        '--td-bg-color-secondarycontainer': '#F5F4EE',
        '--td-bg-color-component': '#FFFEF8',
        '--td-text-color-primary': '#171717',
        '--td-text-color-secondary': '#525252',
        '--td-text-color-placeholder': '#737373',
        '--td-component-border': '#171717',
        '--td-component-stroke': '#171717',
        '--td-border-level-1-color': '#171717',
        '--td-scrollbar-color': '#171717',
        '--graft-scrollbar-track-color': '#D7D7D2',
        '--graft-scrollbar-thumb-hover-color': '#171717',
        '--graft-shell-bg': '#E8E8E5',
        '--graft-shell-header-bg': '#FFFEF8',
        '--graft-shell-sidebar-bg': '#F5F4EE',
        '--graft-shell-content-bg': '#E8E8E5',
        '--graft-shell-border-color': '#171717',
        '--graft-card-bg': '#FFFEF8',
        '--graft-card-bg-hover': '#F2F1EA',
        '--graft-card-border-color': '#171717',
        '--graft-neo-accent': '#FFE45C',
        '--graft-neo-ink': '#171717',
        '--graft-neo-surface': '#FFFEF8',
        '--graft-neo-muted-surface': '#F2F1EA',
        '--graft-neo-shadow': '4px 4px 0 var(--graft-neo-ink)',
      },
      dark: {
        '--td-bg-color-page': '#161616',
        '--td-bg-color-container': '#20201D',
        '--td-bg-color-container-hover': '#2A2A25',
        '--td-bg-color-secondarycontainer': '#1B1B18',
        '--td-bg-color-component': '#20201D',
        '--td-text-color-primary': '#F7F4E8',
        '--td-text-color-secondary': '#CBC6B8',
        '--td-text-color-placeholder': '#999486',
        '--td-component-border': '#F7F4E8',
        '--td-component-stroke': '#F7F4E8',
        '--td-border-level-1-color': '#F7F4E8',
        '--td-scrollbar-color': '#F7F4E8',
        '--graft-scrollbar-track-color': '#292924',
        '--graft-scrollbar-thumb-hover-color': '#F7F4E8',
        '--graft-shell-bg': '#161616',
        '--graft-shell-header-bg': '#20201D',
        '--graft-shell-sidebar-bg': '#1B1B18',
        '--graft-shell-content-bg': '#161616',
        '--graft-shell-border-color': '#F7F4E8',
        '--graft-card-bg': '#20201D',
        '--graft-card-bg-hover': '#2A2A25',
        '--graft-card-border-color': '#F7F4E8',
        '--graft-neo-accent': '#FFE45C',
        '--graft-neo-ink': '#F7F4E8',
        '--graft-neo-surface': '#20201D',
        '--graft-neo-muted-surface': '#2A2A25',
        '--graft-neo-shadow': '4px 4px 0 var(--graft-neo-ink)',
      },
    },
    authorityPatch: {
      fontFamilyPreset: 'system',
      fontSizePreset: 'small',
      radiusPreset: 'square',
      shadowPreset: 'hard-offset',
      densityPreset: 'compact',
    },
    stylePatch: {
      ...SIDE_LAYOUT_STYLE_PATCH,
      isAcrylicEnabled: false,
      isUseTabsRouter: false,
      showFooter: false,
      showHeader: false,
    },
  },
  {
    id: 'tdesign-default',
    labelKey: 'layout.setting.workbench.presets.tdesignDefault.label',
    descriptionKey: 'layout.setting.workbench.presets.tdesignDefault.description',
    category: 'balanced',
    featured: true,
    brandTheme: '#0052D9',
    mode: 'light',
    authorityPatch: STANDARD_SYSTEM_AUTHORITY_PATCH,
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'tencent-cloud',
    labelKey: 'layout.setting.workbench.presets.tencentCloud.label',
    descriptionKey: 'layout.setting.workbench.presets.tencentCloud.description',
    category: 'operations',
    featured: true,
    brandTheme: '#00A4FF',
    mode: 'light',
    tokenOverrides: {
      light: {
        '--td-bg-color-page': '#F4F9FD',
        '--td-bg-color-container': '#FFFFFF',
        '--td-bg-color-secondarycontainer': '#F0F8FF',
        '--td-component-border': '#CBE7F8',
        '--td-component-stroke': '#DCEEF9',
        '--td-scrollbar-color': '#A6D4ED',
        '--graft-scrollbar-track-color': '#E0F1FB',
        '--graft-scrollbar-thumb-hover-color': '#7EC1E8',
        '--graft-shell-bg': '#F4F9FD',
        '--graft-shell-header-bg': '#EAF6FF',
        '--graft-shell-sidebar-bg': '#E5F3FF',
        '--graft-shell-content-bg': '#F4F9FD',
        '--graft-shell-border-color': '#D5EAF8',
        '--graft-card-bg': '#FFFFFF',
        '--graft-card-bg-hover': '#F6FBFF',
        '--graft-card-border-color': '#DCEEF9',
      },
    },
    authorityPatch: {
      fontFamilyPreset: 'inter',
      fontSizePreset: 'standard',
      radiusPreset: 'business',
      shadowPreset: 'standard',
      densityPreset: 'standard',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'mountain-green',
    labelKey: 'layout.setting.workbench.presets.mountainGreen.label',
    descriptionKey: 'layout.setting.workbench.presets.mountainGreen.description',
    category: 'focused',
    brandTheme: '#2BA471',
    mode: 'light',
    authorityPatch: SOURCE_HAN_ROUNDED_AUTHORITY_PATCH,
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'midnight-blue',
    labelKey: 'layout.setting.workbench.presets.midnightBlue.label',
    descriptionKey: 'layout.setting.workbench.presets.midnightBlue.description',
    category: 'night',
    brandTheme: '#3B82F6',
    mode: 'dark',
    authorityPatch: {
      fontFamilyPreset: 'harmonyos',
      fontSizePreset: 'standard',
      radiusPreset: 'standard',
      shadowPreset: 'floating',
      densityPreset: 'comfortable',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'graphite-slate',
    labelKey: 'layout.setting.workbench.presets.graphiteSlate.label',
    descriptionKey: 'layout.setting.workbench.presets.graphiteSlate.description',
    category: 'operations',
    brandTheme: '#4F6B8A',
    mode: 'dark',
    authorityPatch: {
      fontFamilyPreset: 'inter',
      fontSizePreset: 'small',
      radiusPreset: 'business',
      shadowPreset: 'flat',
      densityPreset: 'compact',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      isSidebarFixed: true,
      isUseTabsRouter: true,
      showFooter: true,
      showHeader: true,
      showBreadcrumb: false,
      menuAutoCollapsed: true,
    },
  },
  {
    id: 'sunset-amber',
    labelKey: 'layout.setting.workbench.presets.sunsetAmber.label',
    descriptionKey: 'layout.setting.workbench.presets.sunsetAmber.description',
    category: 'focused',
    brandTheme: '#D97706',
    mode: 'light',
    authorityPatch: {
      fontFamilyPreset: 'source-han-sans',
      fontSizePreset: 'standard',
      radiusPreset: 'rounded',
      shadowPreset: 'standard',
      densityPreset: 'comfortable',
    },
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'ocean-teal',
    labelKey: 'layout.setting.workbench.presets.oceanTeal.label',
    descriptionKey: 'layout.setting.workbench.presets.oceanTeal.description',
    category: 'balanced',
    brandTheme: '#0F8A83',
    mode: 'light',
    authorityPatch: {
      fontFamilyPreset: 'harmonyos',
      fontSizePreset: 'standard',
      radiusPreset: 'standard',
      shadowPreset: 'floating',
      densityPreset: 'standard',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'frost-silver',
    labelKey: 'layout.setting.workbench.presets.frostSilver.label',
    descriptionKey: 'layout.setting.workbench.presets.frostSilver.description',
    category: 'focused',
    brandTheme: '#7A8CA5',
    mode: 'light',
    authorityPatch: {
      fontFamilyPreset: 'system',
      fontSizePreset: 'large',
      radiusPreset: 'capsule',
      shadowPreset: 'flat',
      densityPreset: 'comfortable',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      isSidebarFixed: true,
      isUseTabsRouter: false,
      showFooter: true,
      showHeader: true,
      showBreadcrumb: false,
      menuAutoCollapsed: false,
    },
  },
  {
    id: 'violet-haze',
    labelKey: 'layout.setting.workbench.presets.violetHaze.label',
    descriptionKey: 'layout.setting.workbench.presets.violetHaze.description',
    category: 'balanced',
    brandTheme: '#7562D8',
    mode: 'light',
    tokenOverrides: {
      light: {
        '--td-bg-color-page': '#F8F7FF',
        '--td-bg-color-container': '#FFFFFF',
        '--td-bg-color-secondarycontainer': '#F3F0FF',
        '--td-component-border': '#DED7F7',
        '--td-component-stroke': '#E9E4FA',
        '--td-scrollbar-color': '#C9BFF0',
        '--graft-scrollbar-track-color': '#EEEAFB',
        '--graft-scrollbar-thumb-hover-color': '#AA9BDF',
        '--graft-shell-bg': '#F8F7FF',
        '--graft-shell-header-bg': '#F4F1FF',
        '--graft-shell-sidebar-bg': '#EEEAFE',
        '--graft-shell-content-bg': '#F8F7FF',
        '--graft-shell-border-color': '#E1DBF8',
        '--graft-card-bg': '#FFFFFF',
        '--graft-card-bg-hover': '#FAF9FF',
        '--graft-card-border-color': '#E9E4FA',
      },
    },
    authorityPatch: SOURCE_HAN_ROUNDED_AUTHORITY_PATCH,
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'signal-rose',
    labelKey: 'layout.setting.workbench.presets.signalRose.label',
    descriptionKey: 'layout.setting.workbench.presets.signalRose.description',
    category: 'operations',
    brandTheme: '#D65B8C',
    mode: 'dark',
    tokenOverrides: {
      dark: {
        '--td-bg-color-page': '#171218',
        '--td-bg-color-container': '#211923',
        '--td-bg-color-secondarycontainer': '#1C151E',
        '--td-component-border': '#45313F',
        '--td-component-stroke': '#352633',
        '--td-scrollbar-color': '#735464',
        '--graft-scrollbar-track-color': '#181118',
        '--graft-scrollbar-thumb-hover-color': '#9E7186',
        '--graft-shell-bg': '#171218',
        '--graft-shell-header-bg': '#241A25',
        '--graft-shell-sidebar-bg': '#1B141C',
        '--graft-shell-content-bg': '#171218',
        '--graft-shell-border-color': '#352633',
        '--graft-card-bg': '#211923',
        '--graft-card-bg-hover': '#2A1F2B',
        '--graft-card-border-color': '#352633',
      },
    },
    authorityPatch: {
      fontFamilyPreset: 'inter',
      fontSizePreset: 'small',
      radiusPreset: 'business',
      shadowPreset: 'standard',
      densityPreset: 'compact',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'forest-night',
    labelKey: 'layout.setting.workbench.presets.forestNight.label',
    descriptionKey: 'layout.setting.workbench.presets.forestNight.description',
    category: 'night',
    brandTheme: '#3FA879',
    mode: 'dark',
    tokenOverrides: {
      dark: {
        '--td-bg-color-page': '#101815',
        '--td-bg-color-container': '#17221D',
        '--td-bg-color-secondarycontainer': '#142019',
        '--td-component-border': '#2D4539',
        '--td-component-stroke': '#24382F',
        '--td-scrollbar-color': '#476D5A',
        '--graft-scrollbar-track-color': '#111A15',
        '--graft-scrollbar-thumb-hover-color': '#5D8D73',
        '--graft-shell-bg': '#101815',
        '--graft-shell-header-bg': '#19251F',
        '--graft-shell-sidebar-bg': '#131E18',
        '--graft-shell-content-bg': '#101815',
        '--graft-shell-border-color': '#24382F',
        '--graft-card-bg': '#17221D',
        '--graft-card-bg-hover': '#1D2B24',
        '--graft-card-border-color': '#24382F',
      },
    },
    authorityPatch: {
      fontFamilyPreset: 'harmonyos',
      fontSizePreset: 'standard',
      radiusPreset: 'rounded',
      shadowPreset: 'flat',
      densityPreset: 'comfortable',
    },
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'amethyst-night',
    labelKey: 'layout.setting.workbench.presets.amethystNight.label',
    descriptionKey: 'layout.setting.workbench.presets.amethystNight.description',
    category: 'night',
    brandTheme: '#8A6EDB',
    mode: 'dark',
    tokenOverrides: {
      dark: {
        '--td-bg-color-page': '#15121E',
        '--td-bg-color-container': '#1E192A',
        '--td-bg-color-secondarycontainer': '#191521',
        '--td-component-border': '#3B334F',
        '--td-component-stroke': '#2F2940',
        '--td-scrollbar-color': '#5D5278',
        '--graft-scrollbar-track-color': '#171320',
        '--graft-scrollbar-thumb-hover-color': '#7A6A9C',
        '--graft-shell-bg': '#15121E',
        '--graft-shell-header-bg': '#211B2D',
        '--graft-shell-sidebar-bg': '#191521',
        '--graft-shell-content-bg': '#15121E',
        '--graft-shell-border-color': '#2F2940',
        '--graft-card-bg': '#1E192A',
        '--graft-card-bg-hover': '#272136',
        '--graft-card-border-color': '#2F2940',
      },
    },
    authorityPatch: {
      fontFamilyPreset: 'system',
      fontSizePreset: 'standard',
      radiusPreset: 'standard',
      shadowPreset: 'floating',
      densityPreset: 'standard',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'one-dark-pro',
    labelKey: 'layout.setting.workbench.presets.oneDarkPro.label',
    descriptionKey: 'layout.setting.workbench.presets.oneDarkPro.description',
    category: 'night',
    featured: true,
    brandTheme: '#61AFEF',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#282C34', '#21252B', '#1E2227', '#3E4451', '#2C313A'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(33, 37, 43, 0.72)',
      'rgba(40, 44, 52, 0.78)',
      '0 14px 34px rgba(0, 0, 0, 0.24)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, densityPreset: 'comfortable', shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
  {
    id: 'atom-one-dark',
    labelKey: 'layout.setting.workbench.presets.atomOneDark.label',
    descriptionKey: 'layout.setting.workbench.presets.atomOneDark.description',
    category: 'night',
    brandTheme: '#98C379',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#282C34', '#21252B', '#1B1F24', '#3A414B', '#303640'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(27, 31, 36, 0.74)',
      'rgba(33, 37, 43, 0.8)',
      '0 12px 30px rgba(0, 0, 0, 0.26)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
  {
    id: 'material-oceanic',
    labelKey: 'layout.setting.workbench.presets.materialOceanic.label',
    descriptionKey: 'layout.setting.workbench.presets.materialOceanic.description',
    category: 'night',
    brandTheme: '#80CBC4',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#263238', '#2B3B42', '#1F2A30', '#3B5058', '#34474F'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(43, 59, 66, 0.72)',
      'rgba(50, 68, 75, 0.78)',
      '0 14px 34px rgba(0, 0, 0, 0.26)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, densityPreset: 'comfortable', shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
  {
    id: 'github-dark',
    labelKey: 'layout.setting.workbench.presets.githubDark.label',
    descriptionKey: 'layout.setting.workbench.presets.githubDark.description',
    category: 'operations',
    featured: true,
    brandTheme: '#58A6FF',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#0D1117', '#161B22', '#010409', '#30363D', '#21262D'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(22, 27, 34, 0.74)',
      'rgba(30, 36, 44, 0.8)',
      '0 10px 28px rgba(0, 0, 0, 0.28)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, densityPreset: 'compact' },
    stylePatch: { ...SIDE_LAYOUT_STYLE_PATCH, isAcrylicEnabled: false, isUseTabsRouter: true },
  },
  {
    id: 'dracula',
    labelKey: 'layout.setting.workbench.presets.dracula.label',
    descriptionKey: 'layout.setting.workbench.presets.dracula.description',
    category: 'focused',
    brandTheme: '#BD93F9',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#282A36', '#343746', '#21222C', '#44475A', '#3A3D4D'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(52, 55, 70, 0.72)',
      'rgba(61, 64, 81, 0.78)',
      '0 14px 34px rgba(20, 20, 32, 0.28)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, radiusPreset: 'rounded', shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
  {
    id: 'nord',
    labelKey: 'layout.setting.workbench.presets.nord.label',
    descriptionKey: 'layout.setting.workbench.presets.nord.description',
    category: 'balanced',
    brandTheme: '#88C0D0',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#2E3440', '#3B4252', '#272C36', '#4C566A', '#434C5E'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(59, 66, 82, 0.7)',
      'rgba(70, 78, 96, 0.76)',
      '0 12px 30px rgba(18, 24, 34, 0.24)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, shadowPreset: 'flat' },
    stylePatch: { ...SIDE_LAYOUT_STYLE_PATCH, isAcrylicEnabled: false },
  },
  {
    id: 'tokyo-night',
    labelKey: 'layout.setting.workbench.presets.tokyoNight.label',
    descriptionKey: 'layout.setting.workbench.presets.tokyoNight.description',
    category: 'night',
    featured: true,
    brandTheme: '#7AA2F7',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#1A1B26', '#24283B', '#16161E', '#414868', '#292E42'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(36, 40, 59, 0.72)',
      'rgba(44, 49, 70, 0.78)',
      '0 14px 36px rgba(0, 0, 0, 0.3)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
  {
    id: 'catppuccin-mocha',
    labelKey: 'layout.setting.workbench.presets.catppuccinMocha.label',
    descriptionKey: 'layout.setting.workbench.presets.catppuccinMocha.description',
    category: 'night',
    featured: true,
    brandTheme: '#CBA6F7',
    mode: 'dark',
    tokenOverrides: createDarkPalette('#1E1E2E', '#313244', '#181825', '#45475A', '#3B3D50'),
    materialTokenOverrides: createAcrylicMaterial(
      'rgba(49, 50, 68, 0.72)',
      'rgba(59, 60, 81, 0.78)',
      '0 14px 34px rgba(17, 17, 27, 0.3)',
    ),
    authorityPatch: { ...STANDARD_SYSTEM_AUTHORITY_PATCH, radiusPreset: 'rounded', shadowPreset: 'floating' },
    stylePatch: { ...MIX_LAYOUT_STYLE_PATCH, isAcrylicEnabled: true },
  },
];

export const THEME_WORKBENCH_SCENARIO_PRESETS: ThemeWorkbenchScenarioPresetDefinition[] = [
  {
    id: 'ops-wide',
    labelKey: 'layout.setting.workbench.scenarios.opsWide.label',
    descriptionKey: 'layout.setting.workbench.scenarios.opsWide.description',
    authorityPatch: {
      densityPreset: 'compact',
      shadowPreset: 'standard',
      radiusPreset: 'standard',
    },
    stylePatch: {
      layout: 'mix',
      splitMenu: true,
      isSidebarFixed: true,
      isUseTabsRouter: true,
    },
  },
  {
    id: 'night-watch',
    labelKey: 'layout.setting.workbench.scenarios.nightWatch.label',
    descriptionKey: 'layout.setting.workbench.scenarios.nightWatch.description',
    presetId: 'midnight-blue',
    authorityPatch: {
      mode: 'dark',
      densityPreset: 'comfortable',
      shadowPreset: 'flat',
    },
  },
  {
    id: 'low-distraction',
    labelKey: 'layout.setting.workbench.scenarios.lowDistraction.label',
    descriptionKey: 'layout.setting.workbench.scenarios.lowDistraction.description',
    authorityPatch: {
      mode: 'light',
      densityPreset: 'standard',
      shadowPreset: 'flat',
    },
    stylePatch: {
      showFooter: false,
    },
  },
  {
    id: 'high-density',
    labelKey: 'layout.setting.workbench.scenarios.highDensity.label',
    descriptionKey: 'layout.setting.workbench.scenarios.highDensity.description',
    authorityPatch: {
      densityPreset: 'compact',
      fontSizePreset: 'small',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      showFooter: false,
    },
  },
];
