// Code generated by go generate; DO NOT EDIT.
package moduleregistry

import (
	"graft/server/internal/module"
	auditplugin "graft/server/modules/audit"
	authplugin "graft/server/modules/auth"
	monitorplugin "graft/server/modules/monitor"
	rbacplugin "graft/server/modules/rbac"
	schedulerplugin "graft/server/modules/scheduler"
	userplugin "graft/server/modules/user"
)

var generatedModuleSpecs = []module.Spec{
	auditplugin.NewModuleSpec(),
	authplugin.NewModuleSpec(),
	monitorplugin.NewModuleSpec(),
	rbacplugin.NewModuleSpec(),
	schedulerplugin.NewModuleSpec(),
	userplugin.NewModuleSpec(),
}
