// Package networkopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package networkopenapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetPlatformConnectivityAggregate401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityAggregate401JSONResponseBodySuccessFalse GetPlatformConnectivityAggregate401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityAggregate401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityAggregate401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityAggregate401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityAggregate403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityAggregate403JSONResponseBodySuccessFalse GetPlatformConnectivityAggregate403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityAggregate403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityAggregate403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityAggregate403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityCustomTargets401JSONResponseBodySuccessFalse GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityCustomTargets401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityCustomTargets403JSONResponseBodySuccessFalse GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityCustomTargets403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess.
const (
	PostPlatformConnectivityCustomTarget400JSONResponseBodySuccessFalse PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityCustomTarget400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess.
const (
	PostPlatformConnectivityCustomTarget401JSONResponseBodySuccessFalse PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityCustomTarget401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess.
const (
	PostPlatformConnectivityCustomTarget403JSONResponseBodySuccessFalse PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityCustomTarget403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess.
const (
	DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccessFalse DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess enum.
func (e DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess.
const (
	DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccessFalse DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess enum.
func (e DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess.
const (
	DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccessFalse DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess enum.
func (e DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus.
const (
	GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusDegraded GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus = "degraded"
	GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusFailed   GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus = "failed"
	GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusHealthy  GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus = "healthy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus enum.
func (e GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusDegraded:
		return true
	case GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusFailed:
		return true
	case GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityLatest401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityLatest401JSONResponseBodySuccessFalse GetPlatformConnectivityLatest401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityLatest401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityLatest401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityLatest401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityLatest403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityLatest403JSONResponseBodySuccessFalse GetPlatformConnectivityLatest403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityLatest403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityLatest403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityLatest403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus.
const (
	PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusDegraded PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus = "degraded"
	PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusFailed   PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus = "failed"
	PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusHealthy  PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus = "healthy"
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus enum.
func (e PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus) Valid() bool {
	switch e {
	case PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusDegraded:
		return true
	case PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusFailed:
		return true
	case PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityBatchRun401JSONResponseBodySuccess.
const (
	PostPlatformConnectivityBatchRun401JSONResponseBodySuccessFalse PostPlatformConnectivityBatchRun401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityBatchRun401JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityBatchRun401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityBatchRun401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityBatchRun403JSONResponseBodySuccess.
const (
	PostPlatformConnectivityBatchRun403JSONResponseBodySuccessFalse PostPlatformConnectivityBatchRun403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityBatchRun403JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityBatchRun403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityBatchRun403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory.
const (
	Custom   GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory = "custom"
	General  GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory = "general"
	Git      GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory = "git"
	Oci      GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory = "oci"
	Platform GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory = "platform"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory enum.
func (e GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory) Valid() bool {
	switch e {
	case Custom:
		return true
	case General:
		return true
	case Git:
		return true
	case Oci:
		return true
	case Platform:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures.
const (
	ExitIp     GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures = "exit_ip"
	Export     GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures = "export"
	History    GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures = "history"
	ProxyRoute GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures = "proxy_route"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures enum.
func (e GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures) Valid() bool {
	switch e {
	case ExitIp:
		return true
	case Export:
		return true
	case History:
		return true
	case ProxyRoute:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds.
const (
	Certificate   GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "certificate"
	Dns           GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "dns"
	Http          GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "http"
	LdapBind      GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "ldap_bind"
	OciPing       GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "oci_ping"
	OidcDiscovery GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "oidc_discovery"
	SmtpBanner    GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "smtp_banner"
	SmtpEhlo      GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "smtp_ehlo"
	Tcp           GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "tcp"
	Tls           GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "tls"
	WebhookPost   GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds = "webhook_post"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds enum.
func (e GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds) Valid() bool {
	switch e {
	case Certificate:
		return true
	case Dns:
		return true
	case Http:
		return true
	case LdapBind:
		return true
	case OciPing:
		return true
	case OidcDiscovery:
		return true
	case SmtpBanner:
		return true
	case SmtpEhlo:
		return true
	case Tcp:
		return true
	case Tls:
		return true
	case WebhookPost:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTargets401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityTargets401JSONResponseBodySuccessFalse GetPlatformConnectivityTargets401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTargets401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityTargets401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityTargets401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTargets403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityTargets403JSONResponseBodySuccessFalse GetPlatformConnectivityTargets403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTargets403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityTargets403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityTargets403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus.
const (
	GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusDegraded GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus = "degraded"
	GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusFailed   GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus = "failed"
	GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusHealthy  GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus = "healthy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus enum.
func (e GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusDegraded:
		return true
	case GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusFailed:
		return true
	case GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityHistory400JSONResponseBodySuccess.
const (
	GetPlatformConnectivityHistory400JSONResponseBodySuccessFalse GetPlatformConnectivityHistory400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityHistory400JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityHistory400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityHistory400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityHistory401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityHistory401JSONResponseBodySuccessFalse GetPlatformConnectivityHistory401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityHistory401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityHistory401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityHistory401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityHistory403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityHistory403JSONResponseBodySuccessFalse GetPlatformConnectivityHistory403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityHistory403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityHistory403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityHistory403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus.
const (
	GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusFailed    GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus = "failed"
	GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusSkipped   GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus = "skipped"
	GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusSucceeded GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus enum.
func (e GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusFailed:
		return true
	case GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusSkipped:
		return true
	case GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision.
const (
	GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecisionDirect    GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision = "Direct"
	GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecisionHTTPProxy GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision = "HTTP Proxy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision enum.
func (e GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecisionDirect:
		return true
	case GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecisionHTTPProxy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport200JSONResponseBodyDataStatus.
const (
	GetPlatformConnectivityReport200JSONResponseBodyDataStatusDegraded GetPlatformConnectivityReport200JSONResponseBodyDataStatus = "degraded"
	GetPlatformConnectivityReport200JSONResponseBodyDataStatusFailed   GetPlatformConnectivityReport200JSONResponseBodyDataStatus = "failed"
	GetPlatformConnectivityReport200JSONResponseBodyDataStatusHealthy  GetPlatformConnectivityReport200JSONResponseBodyDataStatus = "healthy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport200JSONResponseBodyDataStatus enum.
func (e GetPlatformConnectivityReport200JSONResponseBodyDataStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport200JSONResponseBodyDataStatusDegraded:
		return true
	case GetPlatformConnectivityReport200JSONResponseBodyDataStatusFailed:
		return true
	case GetPlatformConnectivityReport200JSONResponseBodyDataStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityReport401JSONResponseBodySuccessFalse GetPlatformConnectivityReport401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityReport401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityReport403JSONResponseBodySuccessFalse GetPlatformConnectivityReport403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityReport403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityReport404JSONResponseBodySuccess.
const (
	GetPlatformConnectivityReport404JSONResponseBodySuccessFalse GetPlatformConnectivityReport404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityReport404JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityReport404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityReport404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus.
const (
	GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusFailed    GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus = "failed"
	GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusSkipped   GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus = "skipped"
	GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusSucceeded GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus enum.
func (e GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusFailed:
		return true
	case GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusSkipped:
		return true
	case GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision.
const (
	GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecisionDirect    GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision = "Direct"
	GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecisionHTTPProxy GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision = "HTTP Proxy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision enum.
func (e GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecisionDirect:
		return true
	case GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecisionHTTPProxy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport200JSONResponseBodyDataStatus.
const (
	GetPlatformConnectivityExport200JSONResponseBodyDataStatusDegraded GetPlatformConnectivityExport200JSONResponseBodyDataStatus = "degraded"
	GetPlatformConnectivityExport200JSONResponseBodyDataStatusFailed   GetPlatformConnectivityExport200JSONResponseBodyDataStatus = "failed"
	GetPlatformConnectivityExport200JSONResponseBodyDataStatusHealthy  GetPlatformConnectivityExport200JSONResponseBodyDataStatus = "healthy"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport200JSONResponseBodyDataStatus enum.
func (e GetPlatformConnectivityExport200JSONResponseBodyDataStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport200JSONResponseBodyDataStatusDegraded:
		return true
	case GetPlatformConnectivityExport200JSONResponseBodyDataStatusFailed:
		return true
	case GetPlatformConnectivityExport200JSONResponseBodyDataStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityExport401JSONResponseBodySuccessFalse GetPlatformConnectivityExport401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityExport401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityExport403JSONResponseBodySuccessFalse GetPlatformConnectivityExport403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityExport403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityExport404JSONResponseBodySuccess.
const (
	GetPlatformConnectivityExport404JSONResponseBodySuccessFalse GetPlatformConnectivityExport404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityExport404JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityExport404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityExport404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus.
const (
	GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusFailed    GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus = "failed"
	GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusSkipped   GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus = "skipped"
	GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusSucceeded GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus enum.
func (e GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus) Valid() bool {
	switch e {
	case GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusFailed:
		return true
	case GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusSkipped:
		return true
	case GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTrace401JSONResponseBodySuccess.
const (
	GetPlatformConnectivityTrace401JSONResponseBodySuccessFalse GetPlatformConnectivityTrace401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTrace401JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityTrace401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityTrace401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTrace403JSONResponseBodySuccess.
const (
	GetPlatformConnectivityTrace403JSONResponseBodySuccessFalse GetPlatformConnectivityTrace403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTrace403JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityTrace403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityTrace403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformConnectivityTrace404JSONResponseBodySuccess.
const (
	GetPlatformConnectivityTrace404JSONResponseBodySuccessFalse GetPlatformConnectivityTrace404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetPlatformConnectivityTrace404JSONResponseBodySuccess enum.
func (e GetPlatformConnectivityTrace404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetPlatformConnectivityTrace404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus.
const (
	PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusDegraded PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus = "degraded"
	PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusFailed   PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus = "failed"
	PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusHealthy  PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus = "healthy"
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus enum.
func (e PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus) Valid() bool {
	switch e {
	case PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusDegraded:
		return true
	case PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusFailed:
		return true
	case PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatusHealthy:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus.
const (
	PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusFailed    PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus = "failed"
	PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusSkipped   PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus = "skipped"
	PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusSucceeded PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus enum.
func (e PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus) Valid() bool {
	switch e {
	case PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusFailed:
		return true
	case PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusSkipped:
		return true
	case PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision.
const (
	Direct    PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision = "Direct"
	HTTPProxy PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision = "HTTP Proxy"
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision enum.
func (e PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision) Valid() bool {
	switch e {
	case Direct:
		return true
	case HTTPProxy:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus.
const (
	Degraded PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus = "degraded"
	Failed   PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus = "failed"
	Healthy  PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus = "healthy"
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus enum.
func (e PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Failed:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun401JSONResponseBodySuccess.
const (
	PostPlatformConnectivityRun401JSONResponseBodySuccessFalse PostPlatformConnectivityRun401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun401JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityRun401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityRun401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun403JSONResponseBodySuccess.
const (
	PostPlatformConnectivityRun403JSONResponseBodySuccessFalse PostPlatformConnectivityRun403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun403JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityRun403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostPlatformConnectivityRun403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostPlatformConnectivityRun404JSONResponseBodySuccess.
const (
	False PostPlatformConnectivityRun404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostPlatformConnectivityRun404JSONResponseBodySuccess enum.
func (e PostPlatformConnectivityRun404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// personalAccessTokenAuthContextKey is the context key for personalAccessTokenAuth security scheme
type personalAccessTokenAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetPlatformConnectivityAggregate401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityAggregate.
type GetPlatformConnectivityAggregate401JSONResponseBodySuccess bool

// GetPlatformConnectivityAggregate403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityAggregate.
type GetPlatformConnectivityAggregate403JSONResponseBodySuccess bool

// GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityCustomTargets.
type GetPlatformConnectivityCustomTargets401JSONResponseBodySuccess bool

// GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityCustomTargets.
type GetPlatformConnectivityCustomTargets403JSONResponseBodySuccess bool

// PostPlatformConnectivityCustomTargetJSONBody defines parameters for PostPlatformConnectivityCustomTarget.
type PostPlatformConnectivityCustomTargetJSONBody struct {
	DisplayName string `json:"display_name"`
	Endpoint    string `json:"endpoint"`
	TargetId    string `json:"target_id"`
}

// PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess defines parameters for PostPlatformConnectivityCustomTarget.
type PostPlatformConnectivityCustomTarget400JSONResponseBodySuccess bool

// PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess defines parameters for PostPlatformConnectivityCustomTarget.
type PostPlatformConnectivityCustomTarget401JSONResponseBodySuccess bool

// PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess defines parameters for PostPlatformConnectivityCustomTarget.
type PostPlatformConnectivityCustomTarget403JSONResponseBodySuccess bool

// DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess defines parameters for DeletePlatformConnectivityCustomTarget.
type DeletePlatformConnectivityCustomTarget401JSONResponseBodySuccess bool

// DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess defines parameters for DeletePlatformConnectivityCustomTarget.
type DeletePlatformConnectivityCustomTarget403JSONResponseBodySuccess bool

// DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess defines parameters for DeletePlatformConnectivityCustomTarget.
type DeletePlatformConnectivityCustomTarget404JSONResponseBodySuccess bool

// GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus defines parameters for GetPlatformConnectivityLatest.
type GetPlatformConnectivityLatest200JSONResponseBodyDataItemsStatus string

// GetPlatformConnectivityLatest401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityLatest.
type GetPlatformConnectivityLatest401JSONResponseBodySuccess bool

// GetPlatformConnectivityLatest403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityLatest.
type GetPlatformConnectivityLatest403JSONResponseBodySuccess bool

// PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus defines parameters for PostPlatformConnectivityBatchRun.
type PostPlatformConnectivityBatchRun200JSONResponseBodyDataItemsStatus string

// PostPlatformConnectivityBatchRun401JSONResponseBodySuccess defines parameters for PostPlatformConnectivityBatchRun.
type PostPlatformConnectivityBatchRun401JSONResponseBodySuccess bool

// PostPlatformConnectivityBatchRun403JSONResponseBodySuccess defines parameters for PostPlatformConnectivityBatchRun.
type PostPlatformConnectivityBatchRun403JSONResponseBodySuccess bool

// GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory defines parameters for GetPlatformConnectivityTargets.
type GetPlatformConnectivityTargets200JSONResponseBodyDataItemsCategory string

// GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures defines parameters for GetPlatformConnectivityTargets.
type GetPlatformConnectivityTargets200JSONResponseBodyDataItemsFeatures string

// GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds defines parameters for GetPlatformConnectivityTargets.
type GetPlatformConnectivityTargets200JSONResponseBodyDataItemsProbeKinds string

// GetPlatformConnectivityTargets401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityTargets.
type GetPlatformConnectivityTargets401JSONResponseBodySuccess bool

// GetPlatformConnectivityTargets403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityTargets.
type GetPlatformConnectivityTargets403JSONResponseBodySuccess bool

// GetPlatformConnectivityHistoryParams defines parameters for GetPlatformConnectivityHistory.
type GetPlatformConnectivityHistoryParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus defines parameters for GetPlatformConnectivityHistory.
type GetPlatformConnectivityHistory200JSONResponseBodyDataItemsStatus string

// GetPlatformConnectivityHistory400JSONResponseBodySuccess defines parameters for GetPlatformConnectivityHistory.
type GetPlatformConnectivityHistory400JSONResponseBodySuccess bool

// GetPlatformConnectivityHistory401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityHistory.
type GetPlatformConnectivityHistory401JSONResponseBodySuccess bool

// GetPlatformConnectivityHistory403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityHistory.
type GetPlatformConnectivityHistory403JSONResponseBodySuccess bool

// GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport200JSONResponseBodyDataProbesStatus string

// GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport200JSONResponseBodyDataRouteDecision string

// GetPlatformConnectivityReport200JSONResponseBodyDataStatus defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport200JSONResponseBodyDataStatus string

// GetPlatformConnectivityReport401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport401JSONResponseBodySuccess bool

// GetPlatformConnectivityReport403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport403JSONResponseBodySuccess bool

// GetPlatformConnectivityReport404JSONResponseBodySuccess defines parameters for GetPlatformConnectivityReport.
type GetPlatformConnectivityReport404JSONResponseBodySuccess bool

// GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport200JSONResponseBodyDataProbesStatus string

// GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport200JSONResponseBodyDataRouteDecision string

// GetPlatformConnectivityExport200JSONResponseBodyDataStatus defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport200JSONResponseBodyDataStatus string

// GetPlatformConnectivityExport401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport401JSONResponseBodySuccess bool

// GetPlatformConnectivityExport403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport403JSONResponseBodySuccess bool

// GetPlatformConnectivityExport404JSONResponseBodySuccess defines parameters for GetPlatformConnectivityExport.
type GetPlatformConnectivityExport404JSONResponseBodySuccess bool

// GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus defines parameters for GetPlatformConnectivityTrace.
type GetPlatformConnectivityTrace200JSONResponseBodyDataProbesStatus string

// GetPlatformConnectivityTrace401JSONResponseBodySuccess defines parameters for GetPlatformConnectivityTrace.
type GetPlatformConnectivityTrace401JSONResponseBodySuccess bool

// GetPlatformConnectivityTrace403JSONResponseBodySuccess defines parameters for GetPlatformConnectivityTrace.
type GetPlatformConnectivityTrace403JSONResponseBodySuccess bool

// GetPlatformConnectivityTrace404JSONResponseBodySuccess defines parameters for GetPlatformConnectivityTrace.
type GetPlatformConnectivityTrace404JSONResponseBodySuccess bool

// PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun200JSONResponseBodyDataCheckStatus string

// PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun200JSONResponseBodyDataReportProbesStatus string

// PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun200JSONResponseBodyDataReportRouteDecision string

// PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun200JSONResponseBodyDataReportStatus string

// PostPlatformConnectivityRun401JSONResponseBodySuccess defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun401JSONResponseBodySuccess bool

// PostPlatformConnectivityRun403JSONResponseBodySuccess defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun403JSONResponseBodySuccess bool

// PostPlatformConnectivityRun404JSONResponseBodySuccess defines parameters for PostPlatformConnectivityRun.
type PostPlatformConnectivityRun404JSONResponseBodySuccess bool

// PostPlatformConnectivityCustomTargetJSONRequestBody defines body for PostPlatformConnectivityCustomTarget for application/json ContentType.
type PostPlatformConnectivityCustomTargetJSONRequestBody PostPlatformConnectivityCustomTargetJSONBody
