// Code generated by ent, DO NOT EDIT.

package authpersonalaccesstoken

import (
	"graft/server/modules/auth/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldName, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldSecretHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldRevokedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldDeletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContainsFold(FieldName, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldSecretHash, v))
}

// SecretHashContains applies the Contains predicate on the "secret_hash" field.
func SecretHashContains(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContains(FieldSecretHash, v))
}

// SecretHashHasPrefix applies the HasPrefix predicate on the "secret_hash" field.
func SecretHashHasPrefix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasPrefix(FieldSecretHash, v))
}

// SecretHashHasSuffix applies the HasSuffix predicate on the "secret_hash" field.
func SecretHashHasSuffix(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldHasSuffix(FieldSecretHash, v))
}

// SecretHashEqualFold applies the EqualFold predicate on the "secret_hash" field.
func SecretHashEqualFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEqualFold(FieldSecretHash, v))
}

// SecretHashContainsFold applies the ContainsFold predicate on the "secret_hash" field.
func SecretHashContainsFold(v string) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldContainsFold(FieldSecretHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotNull(FieldRevokedAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.FieldLTE(FieldDeletedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthPersonalAccessToken) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthPersonalAccessToken) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthPersonalAccessToken) predicate.AuthPersonalAccessToken {
	return predicate.AuthPersonalAccessToken(sql.NotPredicates(p))
}
