// Package useropenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package useropenapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetUsers401JSONResponseBodySuccess.
const (
	GetUsers401JSONResponseBodySuccessFalse GetUsers401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUsers401JSONResponseBodySuccess enum.
func (e GetUsers401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUsers401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUsers403JSONResponseBodySuccess.
const (
	GetUsers403JSONResponseBodySuccessFalse GetUsers403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUsers403JSONResponseBodySuccess enum.
func (e GetUsers403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUsers403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUsers500JSONResponseBodySuccess.
const (
	GetUsers500JSONResponseBodySuccessFalse GetUsers500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUsers500JSONResponseBodySuccess enum.
func (e GetUsers500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUsers500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUsers400JSONResponseBodySuccess.
const (
	PostUsers400JSONResponseBodySuccessFalse PostUsers400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUsers400JSONResponseBodySuccess enum.
func (e PostUsers400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUsers400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUsers401JSONResponseBodySuccess.
const (
	PostUsers401JSONResponseBodySuccessFalse PostUsers401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUsers401JSONResponseBodySuccess enum.
func (e PostUsers401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUsers401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUsers403JSONResponseBodySuccess.
const (
	PostUsers403JSONResponseBodySuccessFalse PostUsers403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUsers403JSONResponseBodySuccess enum.
func (e PostUsers403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUsers403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUsers500JSONResponseBodySuccess.
const (
	PostUsers500JSONResponseBodySuccessFalse PostUsers500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUsers500JSONResponseBodySuccess enum.
func (e PostUsers500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUsers500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUserById400JSONResponseBodySuccess.
const (
	GetUserById400JSONResponseBodySuccessFalse GetUserById400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUserById400JSONResponseBodySuccess enum.
func (e GetUserById400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUserById400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUserById401JSONResponseBodySuccess.
const (
	GetUserById401JSONResponseBodySuccessFalse GetUserById401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUserById401JSONResponseBodySuccess enum.
func (e GetUserById401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUserById401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUserById403JSONResponseBodySuccess.
const (
	GetUserById403JSONResponseBodySuccessFalse GetUserById403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUserById403JSONResponseBodySuccess enum.
func (e GetUserById403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUserById403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUserById404JSONResponseBodySuccess.
const (
	GetUserById404JSONResponseBodySuccessFalse GetUserById404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUserById404JSONResponseBodySuccess enum.
func (e GetUserById404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUserById404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetUserById500JSONResponseBodySuccess.
const (
	GetUserById500JSONResponseBodySuccessFalse GetUserById500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetUserById500JSONResponseBodySuccess enum.
func (e GetUserById500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetUserById500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserDelete400JSONResponseBodySuccess.
const (
	PostUserDelete400JSONResponseBodySuccessFalse PostUserDelete400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserDelete400JSONResponseBodySuccess enum.
func (e PostUserDelete400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserDelete400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserDelete401JSONResponseBodySuccess.
const (
	PostUserDelete401JSONResponseBodySuccessFalse PostUserDelete401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserDelete401JSONResponseBodySuccess enum.
func (e PostUserDelete401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserDelete401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserDelete403JSONResponseBodySuccess.
const (
	PostUserDelete403JSONResponseBodySuccessFalse PostUserDelete403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserDelete403JSONResponseBodySuccess enum.
func (e PostUserDelete403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserDelete403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserDelete404JSONResponseBodySuccess.
const (
	PostUserDelete404JSONResponseBodySuccessFalse PostUserDelete404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserDelete404JSONResponseBodySuccess enum.
func (e PostUserDelete404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserDelete404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserDelete500JSONResponseBodySuccess.
const (
	PostUserDelete500JSONResponseBodySuccessFalse PostUserDelete500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserDelete500JSONResponseBodySuccess enum.
func (e PostUserDelete500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserDelete500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserResetPassword400JSONResponseBodySuccess.
const (
	PostUserResetPassword400JSONResponseBodySuccessFalse PostUserResetPassword400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserResetPassword400JSONResponseBodySuccess enum.
func (e PostUserResetPassword400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserResetPassword400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserResetPassword401JSONResponseBodySuccess.
const (
	PostUserResetPassword401JSONResponseBodySuccessFalse PostUserResetPassword401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserResetPassword401JSONResponseBodySuccess enum.
func (e PostUserResetPassword401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserResetPassword401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserResetPassword403JSONResponseBodySuccess.
const (
	PostUserResetPassword403JSONResponseBodySuccessFalse PostUserResetPassword403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserResetPassword403JSONResponseBodySuccess enum.
func (e PostUserResetPassword403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserResetPassword403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserResetPassword404JSONResponseBodySuccess.
const (
	PostUserResetPassword404JSONResponseBodySuccessFalse PostUserResetPassword404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserResetPassword404JSONResponseBodySuccess enum.
func (e PostUserResetPassword404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserResetPassword404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserResetPassword500JSONResponseBodySuccess.
const (
	PostUserResetPassword500JSONResponseBodySuccessFalse PostUserResetPassword500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserResetPassword500JSONResponseBodySuccess enum.
func (e PostUserResetPassword500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserResetPassword500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatusJSONBodyStatus.
const (
	Disabled PostUserStatusJSONBodyStatus = "disabled"
	Enabled  PostUserStatusJSONBodyStatus = "enabled"
)

// Valid indicates whether the value is a known member of the PostUserStatusJSONBodyStatus enum.
func (e PostUserStatusJSONBodyStatus) Valid() bool {
	switch e {
	case Disabled:
		return true
	case Enabled:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatus400JSONResponseBodySuccess.
const (
	PostUserStatus400JSONResponseBodySuccessFalse PostUserStatus400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserStatus400JSONResponseBodySuccess enum.
func (e PostUserStatus400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserStatus400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatus401JSONResponseBodySuccess.
const (
	PostUserStatus401JSONResponseBodySuccessFalse PostUserStatus401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserStatus401JSONResponseBodySuccess enum.
func (e PostUserStatus401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserStatus401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatus403JSONResponseBodySuccess.
const (
	PostUserStatus403JSONResponseBodySuccessFalse PostUserStatus403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserStatus403JSONResponseBodySuccess enum.
func (e PostUserStatus403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserStatus403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatus404JSONResponseBodySuccess.
const (
	PostUserStatus404JSONResponseBodySuccessFalse PostUserStatus404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserStatus404JSONResponseBodySuccess enum.
func (e PostUserStatus404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserStatus404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserStatus500JSONResponseBodySuccess.
const (
	PostUserStatus500JSONResponseBodySuccessFalse PostUserStatus500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserStatus500JSONResponseBodySuccess enum.
func (e PostUserStatus500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserStatus500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserUpdate400JSONResponseBodySuccess.
const (
	PostUserUpdate400JSONResponseBodySuccessFalse PostUserUpdate400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserUpdate400JSONResponseBodySuccess enum.
func (e PostUserUpdate400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserUpdate400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserUpdate401JSONResponseBodySuccess.
const (
	PostUserUpdate401JSONResponseBodySuccessFalse PostUserUpdate401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserUpdate401JSONResponseBodySuccess enum.
func (e PostUserUpdate401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserUpdate401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserUpdate403JSONResponseBodySuccess.
const (
	PostUserUpdate403JSONResponseBodySuccessFalse PostUserUpdate403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserUpdate403JSONResponseBodySuccess enum.
func (e PostUserUpdate403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserUpdate403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserUpdate404JSONResponseBodySuccess.
const (
	PostUserUpdate404JSONResponseBodySuccessFalse PostUserUpdate404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserUpdate404JSONResponseBodySuccess enum.
func (e PostUserUpdate404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserUpdate404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserUpdate500JSONResponseBodySuccess.
const (
	PostUserUpdate500JSONResponseBodySuccessFalse PostUserUpdate500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserUpdate500JSONResponseBodySuccess enum.
func (e PostUserUpdate500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserUpdate500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetUsers401JSONResponseBodySuccess defines parameters for GetUsers.
type GetUsers401JSONResponseBodySuccess bool

// GetUsers403JSONResponseBodySuccess defines parameters for GetUsers.
type GetUsers403JSONResponseBodySuccess bool

// GetUsers500JSONResponseBodySuccess defines parameters for GetUsers.
type GetUsers500JSONResponseBodySuccess bool

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody struct {
	Display string `json:"display"`

	// Password Initial password. The current server policy requires at least 12 characters and both letters and digits.
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostUsersParams defines parameters for PostUsers.
type PostUsersParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostUsers400JSONResponseBodySuccess defines parameters for PostUsers.
type PostUsers400JSONResponseBodySuccess bool

// PostUsers401JSONResponseBodySuccess defines parameters for PostUsers.
type PostUsers401JSONResponseBodySuccess bool

// PostUsers403JSONResponseBodySuccess defines parameters for PostUsers.
type PostUsers403JSONResponseBodySuccess bool

// PostUsers500JSONResponseBodySuccess defines parameters for PostUsers.
type PostUsers500JSONResponseBodySuccess bool

// GetUserByIdParams defines parameters for GetUserById.
type GetUserByIdParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetUserById400JSONResponseBodySuccess defines parameters for GetUserById.
type GetUserById400JSONResponseBodySuccess bool

// GetUserById401JSONResponseBodySuccess defines parameters for GetUserById.
type GetUserById401JSONResponseBodySuccess bool

// GetUserById403JSONResponseBodySuccess defines parameters for GetUserById.
type GetUserById403JSONResponseBodySuccess bool

// GetUserById404JSONResponseBodySuccess defines parameters for GetUserById.
type GetUserById404JSONResponseBodySuccess bool

// GetUserById500JSONResponseBodySuccess defines parameters for GetUserById.
type GetUserById500JSONResponseBodySuccess bool

// PostUserDeleteParams defines parameters for PostUserDelete.
type PostUserDeleteParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostUserDelete400JSONResponseBodySuccess defines parameters for PostUserDelete.
type PostUserDelete400JSONResponseBodySuccess bool

// PostUserDelete401JSONResponseBodySuccess defines parameters for PostUserDelete.
type PostUserDelete401JSONResponseBodySuccess bool

// PostUserDelete403JSONResponseBodySuccess defines parameters for PostUserDelete.
type PostUserDelete403JSONResponseBodySuccess bool

// PostUserDelete404JSONResponseBodySuccess defines parameters for PostUserDelete.
type PostUserDelete404JSONResponseBodySuccess bool

// PostUserDelete500JSONResponseBodySuccess defines parameters for PostUserDelete.
type PostUserDelete500JSONResponseBodySuccess bool

// PostUserResetPasswordJSONBody defines parameters for PostUserResetPassword.
type PostUserResetPasswordJSONBody struct {
	NewPassword string `json:"new_password"`
}

// PostUserResetPasswordParams defines parameters for PostUserResetPassword.
type PostUserResetPasswordParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostUserResetPassword400JSONResponseBodySuccess defines parameters for PostUserResetPassword.
type PostUserResetPassword400JSONResponseBodySuccess bool

// PostUserResetPassword401JSONResponseBodySuccess defines parameters for PostUserResetPassword.
type PostUserResetPassword401JSONResponseBodySuccess bool

// PostUserResetPassword403JSONResponseBodySuccess defines parameters for PostUserResetPassword.
type PostUserResetPassword403JSONResponseBodySuccess bool

// PostUserResetPassword404JSONResponseBodySuccess defines parameters for PostUserResetPassword.
type PostUserResetPassword404JSONResponseBodySuccess bool

// PostUserResetPassword500JSONResponseBodySuccess defines parameters for PostUserResetPassword.
type PostUserResetPassword500JSONResponseBodySuccess bool

// PostUserStatusJSONBody defines parameters for PostUserStatus.
type PostUserStatusJSONBody struct {
	Status PostUserStatusJSONBodyStatus `json:"status"`
}

// PostUserStatusParams defines parameters for PostUserStatus.
type PostUserStatusParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostUserStatusJSONBodyStatus defines parameters for PostUserStatus.
type PostUserStatusJSONBodyStatus string

// PostUserStatus400JSONResponseBodySuccess defines parameters for PostUserStatus.
type PostUserStatus400JSONResponseBodySuccess bool

// PostUserStatus401JSONResponseBodySuccess defines parameters for PostUserStatus.
type PostUserStatus401JSONResponseBodySuccess bool

// PostUserStatus403JSONResponseBodySuccess defines parameters for PostUserStatus.
type PostUserStatus403JSONResponseBodySuccess bool

// PostUserStatus404JSONResponseBodySuccess defines parameters for PostUserStatus.
type PostUserStatus404JSONResponseBodySuccess bool

// PostUserStatus500JSONResponseBodySuccess defines parameters for PostUserStatus.
type PostUserStatus500JSONResponseBodySuccess bool

// PostUserUpdateJSONBody defines parameters for PostUserUpdate.
type PostUserUpdateJSONBody struct {
	Display  string `json:"display"`
	Username string `json:"username"`
}

// PostUserUpdateParams defines parameters for PostUserUpdate.
type PostUserUpdateParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostUserUpdate400JSONResponseBodySuccess defines parameters for PostUserUpdate.
type PostUserUpdate400JSONResponseBodySuccess bool

// PostUserUpdate401JSONResponseBodySuccess defines parameters for PostUserUpdate.
type PostUserUpdate401JSONResponseBodySuccess bool

// PostUserUpdate403JSONResponseBodySuccess defines parameters for PostUserUpdate.
type PostUserUpdate403JSONResponseBodySuccess bool

// PostUserUpdate404JSONResponseBodySuccess defines parameters for PostUserUpdate.
type PostUserUpdate404JSONResponseBodySuccess bool

// PostUserUpdate500JSONResponseBodySuccess defines parameters for PostUserUpdate.
type PostUserUpdate500JSONResponseBodySuccess bool

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// PostUserResetPasswordJSONRequestBody defines body for PostUserResetPassword for application/json ContentType.
type PostUserResetPasswordJSONRequestBody PostUserResetPasswordJSONBody

// PostUserStatusJSONRequestBody defines body for PostUserStatus for application/json ContentType.
type PostUserStatusJSONRequestBody PostUserStatusJSONBody

// PostUserUpdateJSONRequestBody defines body for PostUserUpdate for application/json ContentType.
type PostUserUpdateJSONRequestBody PostUserUpdateJSONBody
