CREATE TABLE IF NOT EXISTS "scheduled_tasks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_key" character varying NOT NULL,
  "task_type" character varying NOT NULL,
  "title" character varying NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "cron_expression" character varying NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "builtin" boolean NOT NULL DEFAULT false,
  "config_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "scheduled_tasks_task_key_key" ON "scheduled_tasks" ("task_key");
CREATE INDEX IF NOT EXISTS "scheduled_tasks_task_type" ON "scheduled_tasks" ("task_type");
CREATE INDEX IF NOT EXISTS "scheduled_tasks_enabled" ON "scheduled_tasks" ("enabled");
CREATE INDEX IF NOT EXISTS "scheduled_tasks_deleted_at" ON "scheduled_tasks" ("deleted_at");

CREATE TABLE IF NOT EXISTS "scheduler_task_runs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_key" character varying NOT NULL,
  "task_name" character varying NOT NULL DEFAULT '',
  "owner" character varying NOT NULL DEFAULT '',
  "module" character varying NOT NULL DEFAULT '',
  "task_type" character varying NOT NULL DEFAULT 'cron',
  "trigger_type" character varying NOT NULL,
  "status" character varying NOT NULL,
  "error" text NOT NULL DEFAULT '',
  "result_summary" text NOT NULL DEFAULT '',
  "error_message" text NOT NULL DEFAULT '',
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz NULL,
  "duration_ms" bigint NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "scheduler_task_runs_task_key_started_at" ON "scheduler_task_runs" ("task_key", "started_at" DESC, "id" DESC);
CREATE INDEX IF NOT EXISTS "scheduler_task_runs_status" ON "scheduler_task_runs" ("status");
CREATE INDEX IF NOT EXISTS "scheduler_task_runs_trigger_type" ON "scheduler_task_runs" ("trigger_type");

COMMENT ON TABLE "scheduled_tasks" IS '定时任务定义表（scheduler 模块）';
COMMENT ON COLUMN "scheduled_tasks"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduled_tasks"."task_key" IS '任务稳定标识';
COMMENT ON COLUMN "scheduled_tasks"."task_type" IS '任务类型：system 或 http';
COMMENT ON COLUMN "scheduled_tasks"."title" IS '任务展示标题';
COMMENT ON COLUMN "scheduled_tasks"."description" IS '任务说明';
COMMENT ON COLUMN "scheduled_tasks"."cron_expression" IS 'cron 表达式';
COMMENT ON COLUMN "scheduled_tasks"."enabled" IS '任务是否启用';
COMMENT ON COLUMN "scheduled_tasks"."builtin" IS '是否为系统内置任务';
COMMENT ON COLUMN "scheduled_tasks"."config_json" IS '任务类型私有配置，HTTP 任务保存 method、url、headers、body、timeout_seconds';
COMMENT ON COLUMN "scheduled_tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "scheduled_tasks"."updated_at" IS '更新时间';
COMMENT ON COLUMN "scheduled_tasks"."deleted_at" IS '软删除时间，为空表示未删除';

COMMENT ON TABLE "scheduler_task_runs" IS '定时任务运行历史表（scheduler 模块）';
COMMENT ON COLUMN "scheduler_task_runs"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduler_task_runs"."task_key" IS '任务稳定标识';
COMMENT ON COLUMN "scheduler_task_runs"."task_name" IS '任务内部名称';
COMMENT ON COLUMN "scheduler_task_runs"."owner" IS '任务所有者或模块标识';
COMMENT ON COLUMN "scheduler_task_runs"."module" IS '注册任务的模块标识';
COMMENT ON COLUMN "scheduler_task_runs"."task_type" IS '任务类型：system 或 http';
COMMENT ON COLUMN "scheduler_task_runs"."trigger_type" IS '触发类型：cron、manual 或 startup';
COMMENT ON COLUMN "scheduler_task_runs"."status" IS '运行状态，如 running、success 或 failed';
COMMENT ON COLUMN "scheduler_task_runs"."error" IS '历史失败错误信息，为空表示无错误';
COMMENT ON COLUMN "scheduler_task_runs"."result_summary" IS '运行结果摘要，不保存完整响应体';
COMMENT ON COLUMN "scheduler_task_runs"."error_message" IS '失败错误摘要，为空表示无错误';
COMMENT ON COLUMN "scheduler_task_runs"."started_at" IS '运行开始时间';
COMMENT ON COLUMN "scheduler_task_runs"."finished_at" IS '运行结束时间';
COMMENT ON COLUMN "scheduler_task_runs"."duration_ms" IS '运行耗时毫秒数';
COMMENT ON COLUMN "scheduler_task_runs"."created_at" IS '记录创建时间';
