// Package applogopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package applogopenapi

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetAppLogsParamsSeverity.
const (
	GetAppLogsParamsSeverityDebug GetAppLogsParamsSeverity = "debug"
	GetAppLogsParamsSeverityError GetAppLogsParamsSeverity = "error"
	GetAppLogsParamsSeverityInfo  GetAppLogsParamsSeverity = "info"
	GetAppLogsParamsSeverityWarn  GetAppLogsParamsSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsSeverity enum.
func (e GetAppLogsParamsSeverity) Valid() bool {
	switch e {
	case GetAppLogsParamsSeverityDebug:
		return true
	case GetAppLogsParamsSeverityError:
		return true
	case GetAppLogsParamsSeverityInfo:
		return true
	case GetAppLogsParamsSeverityWarn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogsParamsSort.
const (
	ComponentAsc   GetAppLogsParamsSort = "component:asc"
	ComponentDesc  GetAppLogsParamsSort = "component:desc"
	OccurredAtAsc  GetAppLogsParamsSort = "occurred_at:asc"
	OccurredAtDesc GetAppLogsParamsSort = "occurred_at:desc"
	SeverityAsc    GetAppLogsParamsSort = "severity:asc"
	SeverityDesc   GetAppLogsParamsSort = "severity:desc"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsSort enum.
func (e GetAppLogsParamsSort) Valid() bool {
	switch e {
	case ComponentAsc:
		return true
	case ComponentDesc:
		return true
	case OccurredAtAsc:
		return true
	case OccurredAtDesc:
		return true
	case SeverityAsc:
		return true
	case SeverityDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs200JSONResponseBodyDataItemsSeverity.
const (
	GetAppLogs200JSONResponseBodyDataItemsSeverityDebug GetAppLogs200JSONResponseBodyDataItemsSeverity = "debug"
	GetAppLogs200JSONResponseBodyDataItemsSeverityError GetAppLogs200JSONResponseBodyDataItemsSeverity = "error"
	GetAppLogs200JSONResponseBodyDataItemsSeverityInfo  GetAppLogs200JSONResponseBodyDataItemsSeverity = "info"
	GetAppLogs200JSONResponseBodyDataItemsSeverityWarn  GetAppLogs200JSONResponseBodyDataItemsSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogs200JSONResponseBodyDataItemsSeverity enum.
func (e GetAppLogs200JSONResponseBodyDataItemsSeverity) Valid() bool {
	switch e {
	case GetAppLogs200JSONResponseBodyDataItemsSeverityDebug:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityError:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityInfo:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityWarn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs400JSONResponseBodySuccess.
const (
	GetAppLogs400JSONResponseBodySuccessFalse GetAppLogs400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs400JSONResponseBodySuccess enum.
func (e GetAppLogs400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs401JSONResponseBodySuccess.
const (
	GetAppLogs401JSONResponseBodySuccessFalse GetAppLogs401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs401JSONResponseBodySuccess enum.
func (e GetAppLogs401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs403JSONResponseBodySuccess.
const (
	GetAppLogs403JSONResponseBodySuccessFalse GetAppLogs403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs403JSONResponseBodySuccess enum.
func (e GetAppLogs403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs500JSONResponseBodySuccess.
const (
	GetAppLogs500JSONResponseBodySuccessFalse GetAppLogs500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs500JSONResponseBodySuccess enum.
func (e GetAppLogs500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion400JSONResponseBodySuccess.
const (
	PostAppLogDeletion400JSONResponseBodySuccessFalse PostAppLogDeletion400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion400JSONResponseBodySuccess enum.
func (e PostAppLogDeletion400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion401JSONResponseBodySuccess.
const (
	PostAppLogDeletion401JSONResponseBodySuccessFalse PostAppLogDeletion401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion401JSONResponseBodySuccess enum.
func (e PostAppLogDeletion401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion403JSONResponseBodySuccess.
const (
	PostAppLogDeletion403JSONResponseBodySuccessFalse PostAppLogDeletion403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion403JSONResponseBodySuccess enum.
func (e PostAppLogDeletion403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion404JSONResponseBodySuccess.
const (
	PostAppLogDeletion404JSONResponseBodySuccessFalse PostAppLogDeletion404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion404JSONResponseBodySuccess enum.
func (e PostAppLogDeletion404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion409JSONResponseBodySuccess.
const (
	PostAppLogDeletion409JSONResponseBodySuccessFalse PostAppLogDeletion409JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion409JSONResponseBodySuccess enum.
func (e PostAppLogDeletion409JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion409JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogDeletion500JSONResponseBodySuccess.
const (
	PostAppLogDeletion500JSONResponseBodySuccessFalse PostAppLogDeletion500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogDeletion500JSONResponseBodySuccess enum.
func (e PostAppLogDeletion500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogDeletion500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogSavedViews401JSONResponseBodySuccess.
const (
	GetAppLogSavedViews401JSONResponseBodySuccessFalse GetAppLogSavedViews401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogSavedViews401JSONResponseBodySuccess enum.
func (e GetAppLogSavedViews401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogSavedViews401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogSavedViews403JSONResponseBodySuccess.
const (
	GetAppLogSavedViews403JSONResponseBodySuccessFalse GetAppLogSavedViews403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogSavedViews403JSONResponseBodySuccess enum.
func (e GetAppLogSavedViews403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogSavedViews403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogSavedView401JSONResponseBodySuccess.
const (
	PostAppLogSavedView401JSONResponseBodySuccessFalse PostAppLogSavedView401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogSavedView401JSONResponseBodySuccess enum.
func (e PostAppLogSavedView401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogSavedView401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogSavedView403JSONResponseBodySuccess.
const (
	PostAppLogSavedView403JSONResponseBodySuccessFalse PostAppLogSavedView403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogSavedView403JSONResponseBodySuccess enum.
func (e PostAppLogSavedView403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogSavedView403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLogSavedView401JSONResponseBodySuccess.
const (
	DeleteAppLogSavedView401JSONResponseBodySuccessFalse DeleteAppLogSavedView401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLogSavedView401JSONResponseBodySuccess enum.
func (e DeleteAppLogSavedView401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLogSavedView401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLogSavedView403JSONResponseBodySuccess.
const (
	DeleteAppLogSavedView403JSONResponseBodySuccessFalse DeleteAppLogSavedView403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLogSavedView403JSONResponseBodySuccess enum.
func (e DeleteAppLogSavedView403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLogSavedView403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PutAppLogSavedView401JSONResponseBodySuccess.
const (
	PutAppLogSavedView401JSONResponseBodySuccessFalse PutAppLogSavedView401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PutAppLogSavedView401JSONResponseBodySuccess enum.
func (e PutAppLogSavedView401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PutAppLogSavedView401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PutAppLogSavedView403JSONResponseBodySuccess.
const (
	PutAppLogSavedView403JSONResponseBodySuccessFalse PutAppLogSavedView403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PutAppLogSavedView403JSONResponseBodySuccess enum.
func (e PutAppLogSavedView403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PutAppLogSavedView403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail200JSONResponseBodyDataSeverity.
const (
	Debug GetAppLogDetail200JSONResponseBodyDataSeverity = "debug"
	Error GetAppLogDetail200JSONResponseBodyDataSeverity = "error"
	Info  GetAppLogDetail200JSONResponseBodyDataSeverity = "info"
	Warn  GetAppLogDetail200JSONResponseBodyDataSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogDetail200JSONResponseBodyDataSeverity enum.
func (e GetAppLogDetail200JSONResponseBodyDataSeverity) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail400JSONResponseBodySuccess.
const (
	GetAppLogDetail400JSONResponseBodySuccessFalse GetAppLogDetail400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail400JSONResponseBodySuccess enum.
func (e GetAppLogDetail400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail401JSONResponseBodySuccess.
const (
	GetAppLogDetail401JSONResponseBodySuccessFalse GetAppLogDetail401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail401JSONResponseBodySuccess enum.
func (e GetAppLogDetail401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail403JSONResponseBodySuccess.
const (
	GetAppLogDetail403JSONResponseBodySuccessFalse GetAppLogDetail403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail403JSONResponseBodySuccess enum.
func (e GetAppLogDetail403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail404JSONResponseBodySuccess.
const (
	GetAppLogDetail404JSONResponseBodySuccessFalse GetAppLogDetail404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail404JSONResponseBodySuccess enum.
func (e GetAppLogDetail404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail500JSONResponseBodySuccess.
const (
	False GetAppLogDetail500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail500JSONResponseBodySuccess enum.
func (e GetAppLogDetail500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// personalAccessTokenAuthContextKey is the context key for personalAccessTokenAuth security scheme
type personalAccessTokenAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// OccurredFrom Inclusive canonical occurrence-time lower bound on `occurred_at`.
	OccurredFrom *time.Time `form:"occurred_from,omitempty" json:"occurred_from,omitempty"`

	// OccurredTo Inclusive canonical occurrence-time upper bound on `occurred_at`.
	OccurredTo *time.Time                `form:"occurred_to,omitempty" json:"occurred_to,omitempty"`
	Severity   *GetAppLogsParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`

	// Category Category text for durable App Log records. The server validates it against the logger Category Registry.
	Category  *string `form:"category,omitempty" json:"category,omitempty"`
	Component *string `form:"component,omitempty" json:"component,omitempty"`
	Operation *string `form:"operation,omitempty" json:"operation,omitempty"`
	RequestId *string `form:"request_id,omitempty" json:"request_id,omitempty"`
	TraceId   *string `form:"trace_id,omitempty" json:"trace_id,omitempty"`

	// Keyword Canonical fuzzy match applied to component, operation, message, and error.
	Keyword *string `form:"keyword,omitempty" json:"keyword,omitempty"`

	// Message Bounded fuzzy match applied to the app-log message only.
	Message *string `form:"message,omitempty" json:"message,omitempty"`

	// Error Bounded fuzzy match applied to the app-log error text only.
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// Sort Repeated sort fields encoded as `field:direction`.
	Sort *[]GetAppLogsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAppLogsParamsSeverity defines parameters for GetAppLogs.
type GetAppLogsParamsSeverity string

// GetAppLogsParamsSort defines parameters for GetAppLogs.
type GetAppLogsParamsSort string

// GetAppLogs200JSONResponseBodyDataItemsSeverity defines parameters for GetAppLogs.
type GetAppLogs200JSONResponseBodyDataItemsSeverity string

// GetAppLogs400JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs400JSONResponseBodySuccess bool

// GetAppLogs401JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs401JSONResponseBodySuccess bool

// GetAppLogs403JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs403JSONResponseBodySuccess bool

// GetAppLogs500JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs500JSONResponseBodySuccess bool

// PostAppLogDeletionJSONBody defines parameters for PostAppLogDeletion.
type PostAppLogDeletionJSONBody struct {
	Ids []int64 `json:"ids"`
}

// PostAppLogDeletionParams defines parameters for PostAppLogDeletion.
type PostAppLogDeletionParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId     *string `json:"X-Request-Id,omitempty"`
	IdempotencyKey string  `json:"Idempotency-Key"`
}

// PostAppLogDeletion400JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion400JSONResponseBodySuccess bool

// PostAppLogDeletion401JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion401JSONResponseBodySuccess bool

// PostAppLogDeletion403JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion403JSONResponseBodySuccess bool

// PostAppLogDeletion404JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion404JSONResponseBodySuccess bool

// PostAppLogDeletion409JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion409JSONResponseBodySuccess bool

// PostAppLogDeletion500JSONResponseBodySuccess defines parameters for PostAppLogDeletion.
type PostAppLogDeletion500JSONResponseBodySuccess bool

// GetAppLogSavedViewsParams defines parameters for GetAppLogSavedViews.
type GetAppLogSavedViewsParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAppLogSavedViews401JSONResponseBodySuccess defines parameters for GetAppLogSavedViews.
type GetAppLogSavedViews401JSONResponseBodySuccess bool

// GetAppLogSavedViews403JSONResponseBodySuccess defines parameters for GetAppLogSavedViews.
type GetAppLogSavedViews403JSONResponseBodySuccess bool

// PostAppLogSavedViewJSONBody defines parameters for PostAppLogSavedView.
type PostAppLogSavedViewJSONBody struct {
	// IsDefault Whether this view becomes the user's default for this list surface.
	IsDefault      *bool                  `json:"is_default,omitempty"`
	Name           string                 `json:"name"`
	PageSize       int                    `json:"page_size"`
	QueryState     map[string]interface{} `json:"query_state"`
	VisibleColumns []string               `json:"visible_columns"`
}

// PostAppLogSavedViewParams defines parameters for PostAppLogSavedView.
type PostAppLogSavedViewParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostAppLogSavedView401JSONResponseBodySuccess defines parameters for PostAppLogSavedView.
type PostAppLogSavedView401JSONResponseBodySuccess bool

// PostAppLogSavedView403JSONResponseBodySuccess defines parameters for PostAppLogSavedView.
type PostAppLogSavedView403JSONResponseBodySuccess bool

// DeleteAppLogSavedViewParams defines parameters for DeleteAppLogSavedView.
type DeleteAppLogSavedViewParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// DeleteAppLogSavedView401JSONResponseBodySuccess defines parameters for DeleteAppLogSavedView.
type DeleteAppLogSavedView401JSONResponseBodySuccess bool

// DeleteAppLogSavedView403JSONResponseBodySuccess defines parameters for DeleteAppLogSavedView.
type DeleteAppLogSavedView403JSONResponseBodySuccess bool

// PutAppLogSavedViewJSONBody defines parameters for PutAppLogSavedView.
type PutAppLogSavedViewJSONBody struct {
	// IsDefault Whether this view becomes the user's default for this list surface.
	IsDefault      *bool                  `json:"is_default,omitempty"`
	Name           string                 `json:"name"`
	PageSize       int                    `json:"page_size"`
	QueryState     map[string]interface{} `json:"query_state"`
	VisibleColumns []string               `json:"visible_columns"`
}

// PutAppLogSavedViewParams defines parameters for PutAppLogSavedView.
type PutAppLogSavedViewParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PutAppLogSavedView401JSONResponseBodySuccess defines parameters for PutAppLogSavedView.
type PutAppLogSavedView401JSONResponseBodySuccess bool

// PutAppLogSavedView403JSONResponseBodySuccess defines parameters for PutAppLogSavedView.
type PutAppLogSavedView403JSONResponseBodySuccess bool

// GetAppLogDetailParams defines parameters for GetAppLogDetail.
type GetAppLogDetailParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAppLogDetail200JSONResponseBodyDataSeverity defines parameters for GetAppLogDetail.
type GetAppLogDetail200JSONResponseBodyDataSeverity string

// GetAppLogDetail400JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail400JSONResponseBodySuccess bool

// GetAppLogDetail401JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail401JSONResponseBodySuccess bool

// GetAppLogDetail403JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail403JSONResponseBodySuccess bool

// GetAppLogDetail404JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail404JSONResponseBodySuccess bool

// GetAppLogDetail500JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail500JSONResponseBodySuccess bool

// PostAppLogDeletionJSONRequestBody defines body for PostAppLogDeletion for application/json ContentType.
type PostAppLogDeletionJSONRequestBody PostAppLogDeletionJSONBody

// PostAppLogSavedViewJSONRequestBody defines body for PostAppLogSavedView for application/json ContentType.
type PostAppLogSavedViewJSONRequestBody PostAppLogSavedViewJSONBody

// PutAppLogSavedViewJSONRequestBody defines body for PutAppLogSavedView for application/json ContentType.
type PutAppLogSavedViewJSONRequestBody PutAppLogSavedViewJSONBody
