CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  task_type varchar(191) NOT NULL,
  owner_type varchar(64) NOT NULL,
  owner_id varchar(191) NOT NULL,
  status varchar(32) NOT NULL,
  input_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  plan_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_stage_key varchar(128) NULL,
  created_by bigint NULL,
  scheduled_at timestamptz NULL,
  cancel_requested_at timestamptz NULL,
  started_at timestamptz NULL,
  finished_at timestamptz NULL,
  duration_ms bigint NULL,
  failure_code varchar(128) NULL,
  failure_message text NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT tasks_type_not_blank CHECK (btrim(task_type) <> ''),
  CONSTRAINT tasks_owner_type_not_blank CHECK (btrim(owner_type) <> ''),
  CONSTRAINT tasks_owner_id_not_blank CHECK (btrim(owner_id) <> ''),
  CONSTRAINT tasks_status_check CHECK (status IN ('pending', 'scheduled', 'running', 'success', 'failed', 'cancelled', 'needs_attention')),
  CONSTRAINT tasks_duration_non_negative CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE INDEX idx_tasks_owner_created_at ON tasks (owner_type, owner_id, created_at DESC, id DESC);
CREATE INDEX idx_tasks_status_scheduled_at ON tasks (status, scheduled_at ASC NULLS LAST, id ASC);
CREATE UNIQUE INDEX uq_tasks_active_owner ON tasks (owner_type, owner_id)
  WHERE status IN ('pending', 'scheduled', 'running', 'needs_attention');

CREATE TABLE task_stages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  task_id bigint NOT NULL,
  stage_key varchar(128) NOT NULL,
  sequence integer NOT NULL,
  executor_type varchar(191) NOT NULL,
  status varchar(32) NOT NULL,
  attempt integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 1,
  retry_backoff_ms bigint NOT NULL DEFAULT 0,
  next_retry_at timestamptz NULL,
  input_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  recovery_policy varchar(32) NOT NULL,
  result_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  failure_code varchar(128) NULL,
  failure_message text NULL,
  started_at timestamptz NULL,
  finished_at timestamptz NULL,
  duration_ms bigint NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT task_stages_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE RESTRICT,
  CONSTRAINT task_stages_key_not_blank CHECK (btrim(stage_key) <> ''),
  CONSTRAINT task_stages_executor_type_not_blank CHECK (btrim(executor_type) <> ''),
  CONSTRAINT task_stages_sequence_positive CHECK (sequence > 0),
  CONSTRAINT task_stages_status_check CHECK (status IN ('pending', 'running', 'success', 'failed', 'skipped', 'cancelled', 'unknown')),
  CONSTRAINT task_stages_attempt_non_negative CHECK (attempt >= 0),
  CONSTRAINT task_stages_max_attempts_positive CHECK (max_attempts >= 1),
  CONSTRAINT task_stages_retry_backoff_non_negative CHECK (retry_backoff_ms >= 0),
  CONSTRAINT task_stages_recovery_policy_check CHECK (recovery_policy IN ('manual_reconcile', 'retry_if_idempotent')),
  CONSTRAINT task_stages_duration_non_negative CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE UNIQUE INDEX uq_task_stages_task_sequence ON task_stages (task_id, sequence);
CREATE UNIQUE INDEX uq_task_stages_task_key ON task_stages (task_id, stage_key);
CREATE INDEX idx_task_stages_task_status_sequence ON task_stages (task_id, status, sequence ASC);
CREATE INDEX idx_task_stages_dispatch ON task_stages (status, next_retry_at ASC NULLS FIRST, id ASC);

CREATE TABLE task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  task_id bigint NOT NULL,
  sequence bigint NOT NULL,
  event_type varchar(32) NOT NULL,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT task_events_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE RESTRICT,
  CONSTRAINT task_events_sequence_positive CHECK (sequence > 0),
  CONSTRAINT task_events_type_check CHECK (event_type IN ('created', 'cancel_requested', 'cancelled', 'retry_requested', 'retry_scheduled', 'recovery_required', 'recovery_resolved'))
);

CREATE UNIQUE INDEX uq_task_events_task_sequence ON task_events (task_id, sequence);

CREATE TABLE task_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  task_id bigint NOT NULL,
  stage_id bigint NULL,
  sequence bigint NOT NULL,
  stream varchar(16) NOT NULL,
  level varchar(16) NOT NULL,
  line text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT task_logs_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE RESTRICT,
  CONSTRAINT task_logs_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES task_stages (id) ON DELETE RESTRICT,
  CONSTRAINT task_logs_sequence_positive CHECK (sequence > 0),
  CONSTRAINT task_logs_stream_check CHECK (stream IN ('stdout', 'stderr', 'system')),
  CONSTRAINT task_logs_level_check CHECK (level IN ('info', 'warn', 'error')),
  CONSTRAINT task_logs_line_not_blank CHECK (btrim(line) <> '')
);

CREATE UNIQUE INDEX uq_task_logs_task_sequence ON task_logs (task_id, sequence);
CREATE INDEX idx_task_logs_task_stage_sequence ON task_logs (task_id, stage_id, sequence ASC);

COMMENT ON TABLE tasks IS '任务运行时任务执行事实表';
COMMENT ON COLUMN tasks.id IS '任务执行主键';
COMMENT ON COLUMN tasks.task_type IS '业务模块定义的稳定任务类型';
COMMENT ON COLUMN tasks.owner_type IS '任务所属业务资源类型';
COMMENT ON COLUMN tasks.owner_id IS '任务所属业务资源稳定标识';
COMMENT ON COLUMN tasks.status IS '任务状态机状态';
COMMENT ON COLUMN tasks.input_json IS '任务提交时冻结的业务输入 JSON';
COMMENT ON COLUMN tasks.metadata_json IS '可展示且已脱敏的任务元数据 JSON';
COMMENT ON COLUMN tasks.plan_json IS '提交时冻结的串行任务计划 JSON';
COMMENT ON COLUMN tasks.state_json IS '运行时维护的任务内部状态 JSON';
COMMENT ON COLUMN tasks.current_stage_key IS '当前或最近处理的阶段稳定标识';
COMMENT ON COLUMN tasks.created_by IS '提交任务的用户 ID，系统任务为空';
COMMENT ON COLUMN tasks.scheduled_at IS '允许任务开始执行的计划时间';
COMMENT ON COLUMN tasks.cancel_requested_at IS '操作者请求取消任务的时间';
COMMENT ON COLUMN tasks.started_at IS '任务首次开始执行的时间';
COMMENT ON COLUMN tasks.finished_at IS '任务进入终态的时间';
COMMENT ON COLUMN tasks.duration_ms IS '任务终态耗时，单位毫秒';
COMMENT ON COLUMN tasks.failure_code IS '任务失败或需人工处理的稳定错误码';
COMMENT ON COLUMN tasks.failure_message IS '任务失败或需人工处理的诊断摘要';
COMMENT ON COLUMN tasks.created_at IS '任务执行记录创建时间';
COMMENT ON COLUMN tasks.updated_at IS '任务执行记录最近状态更新时间';
COMMENT ON INDEX uq_tasks_active_owner IS '同一业务资源仅允许一个活跃任务执行';

COMMENT ON TABLE task_stages IS '任务运行时冻结阶段执行事实表';
COMMENT ON COLUMN task_stages.id IS '任务阶段执行主键';
COMMENT ON COLUMN task_stages.task_id IS '所属任务执行主键';
COMMENT ON COLUMN task_stages.stage_key IS '任务计划内稳定阶段标识';
COMMENT ON COLUMN task_stages.sequence IS '串行阶段执行顺序，从一开始';
COMMENT ON COLUMN task_stages.executor_type IS '业务模块注册的阶段执行器类型';
COMMENT ON COLUMN task_stages.status IS '阶段状态机状态';
COMMENT ON COLUMN task_stages.attempt IS '当前阶段执行尝试次数';
COMMENT ON COLUMN task_stages.max_attempts IS '冻结计划允许的最大执行尝试次数';
COMMENT ON COLUMN task_stages.retry_backoff_ms IS '重试等待时长，单位毫秒';
COMMENT ON COLUMN task_stages.next_retry_at IS '允许下一次重试的最早时间';
COMMENT ON COLUMN task_stages.input_json IS '冻结的阶段执行器输入 JSON';
COMMENT ON COLUMN task_stages.recovery_policy IS '进程中断后的阶段恢复策略';
COMMENT ON COLUMN task_stages.result_json IS '阶段执行结果摘要 JSON';
COMMENT ON COLUMN task_stages.failure_code IS '阶段失败或未知状态的稳定错误码';
COMMENT ON COLUMN task_stages.failure_message IS '阶段失败或未知状态的诊断摘要';
COMMENT ON COLUMN task_stages.started_at IS '阶段最近一次开始执行的时间';
COMMENT ON COLUMN task_stages.finished_at IS '阶段最近一次进入终态的时间';
COMMENT ON COLUMN task_stages.duration_ms IS '阶段终态耗时，单位毫秒';
COMMENT ON COLUMN task_stages.created_at IS '阶段执行记录创建时间';
COMMENT ON COLUMN task_stages.updated_at IS '阶段执行记录最近状态更新时间';

COMMENT ON TABLE task_events IS '任务运行时不可推导生命周期事件表';
COMMENT ON COLUMN task_events.id IS '任务事件主键';
COMMENT ON COLUMN task_events.task_id IS '所属任务执行主键';
COMMENT ON COLUMN task_events.sequence IS '任务内单调递增事件序号';
COMMENT ON COLUMN task_events.event_type IS '不可由任务或阶段行推导的生命周期事件类型';
COMMENT ON COLUMN task_events.payload_json IS '事件附加事实 JSON';
COMMENT ON COLUMN task_events.created_at IS '任务事件写入时间';

COMMENT ON TABLE task_logs IS '任务运行时阶段输出与系统诊断日志表';
COMMENT ON COLUMN task_logs.id IS '任务日志主键';
COMMENT ON COLUMN task_logs.task_id IS '所属任务执行主键';
COMMENT ON COLUMN task_logs.stage_id IS '关联阶段执行主键，系统日志为空';
COMMENT ON COLUMN task_logs.sequence IS '任务内单调递增日志序号';
COMMENT ON COLUMN task_logs.stream IS '日志来源流，stdout、stderr 或 system';
COMMENT ON COLUMN task_logs.level IS '日志级别，info、warn 或 error';
COMMENT ON COLUMN task_logs.line IS '已脱敏的单条日志文本';
COMMENT ON COLUMN task_logs.occurred_at IS '日志产生或写入时间';
