// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"graft/server/modules/auth/ent/authpersonalaccesstoken"
	"graft/server/modules/auth/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// AuthPersonalAccessTokenUpdate is the builder for updating AuthPersonalAccessToken entities.
type AuthPersonalAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *AuthPersonalAccessTokenMutation
}

// Where appends a list predicates to the AuthPersonalAccessTokenUpdate builder.
func (_u *AuthPersonalAccessTokenUpdate) Where(ps ...predicate.AuthPersonalAccessToken) *AuthPersonalAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AuthPersonalAccessTokenUpdate) SetName(v string) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdate) SetNillableName(v *string) *AuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AuthPersonalAccessTokenUpdate) SetScopes(v []string) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AuthPersonalAccessTokenUpdate) AppendScopes(v []string) *AuthPersonalAccessTokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthPersonalAccessTokenUpdate) SetExpiresAt(v time.Time) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *AuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthPersonalAccessTokenUpdate) SetRevokedAt(v time.Time) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdate) SetNillableRevokedAt(v *time.Time) *AuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthPersonalAccessTokenUpdate) ClearRevokedAt() *AuthPersonalAccessTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AuthPersonalAccessTokenUpdate) SetLastUsedAt(v time.Time) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdate) SetNillableLastUsedAt(v *time.Time) *AuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AuthPersonalAccessTokenUpdate) ClearLastUsedAt() *AuthPersonalAccessTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthPersonalAccessTokenUpdate) SetUpdatedAt(v time.Time) *AuthPersonalAccessTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthPersonalAccessTokenUpdate) SetDeletedAt(v int64) *AuthPersonalAccessTokenUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdate) SetNillableDeletedAt(v *int64) *AuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AuthPersonalAccessTokenUpdate) AddDeletedAt(v int64) *AuthPersonalAccessTokenUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// Mutation returns the AuthPersonalAccessTokenMutation object of the builder.
func (_u *AuthPersonalAccessTokenUpdate) Mutation() *AuthPersonalAccessTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthPersonalAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthPersonalAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthPersonalAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthPersonalAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthPersonalAccessTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authpersonalaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthPersonalAccessTokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := authpersonalaccesstoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AuthPersonalAccessToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthPersonalAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authpersonalaccesstoken.Table, authpersonalaccesstoken.Columns, sqlgraph.NewFieldSpec(authpersonalaccesstoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authpersonalaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authpersonalaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(authpersonalaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(authpersonalaccesstoken.FieldDeletedAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authpersonalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthPersonalAccessTokenUpdateOne is the builder for updating a single AuthPersonalAccessToken entity.
type AuthPersonalAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthPersonalAccessTokenMutation
}

// SetName sets the "name" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetName(v string) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdateOne) SetNillableName(v *string) *AuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetScopes(v []string) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AuthPersonalAccessTokenUpdateOne) AppendScopes(v []string) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetExpiresAt(v time.Time) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetRevokedAt(v time.Time) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *AuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) ClearRevokedAt() *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetLastUsedAt(v time.Time) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *AuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) ClearLastUsedAt() *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetUpdatedAt(v time.Time) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) SetDeletedAt(v int64) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthPersonalAccessTokenUpdateOne) SetNillableDeletedAt(v *int64) *AuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AuthPersonalAccessTokenUpdateOne) AddDeletedAt(v int64) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// Mutation returns the AuthPersonalAccessTokenMutation object of the builder.
func (_u *AuthPersonalAccessTokenUpdateOne) Mutation() *AuthPersonalAccessTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthPersonalAccessTokenUpdate builder.
func (_u *AuthPersonalAccessTokenUpdateOne) Where(ps ...predicate.AuthPersonalAccessToken) *AuthPersonalAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthPersonalAccessTokenUpdateOne) Select(field string, fields ...string) *AuthPersonalAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthPersonalAccessToken entity.
func (_u *AuthPersonalAccessTokenUpdateOne) Save(ctx context.Context) (*AuthPersonalAccessToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthPersonalAccessTokenUpdateOne) SaveX(ctx context.Context) *AuthPersonalAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthPersonalAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthPersonalAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthPersonalAccessTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authpersonalaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthPersonalAccessTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := authpersonalaccesstoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AuthPersonalAccessToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthPersonalAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *AuthPersonalAccessToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authpersonalaccesstoken.Table, authpersonalaccesstoken.Columns, sqlgraph.NewFieldSpec(authpersonalaccesstoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthPersonalAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authpersonalaccesstoken.FieldID)
		for _, f := range fields {
			if !authpersonalaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authpersonalaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authpersonalaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authpersonalaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(authpersonalaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authpersonalaccesstoken.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(authpersonalaccesstoken.FieldDeletedAt, field.TypeInt64, value)
	}
	_node = &AuthPersonalAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authpersonalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
