// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"graft/server/modules/auth/ent/authrefreshsession"
	"graft/server/modules/auth/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthRefreshSessionDelete is the builder for deleting a AuthRefreshSession entity.
type AuthRefreshSessionDelete struct {
	config
	hooks    []Hook
	mutation *AuthRefreshSessionMutation
}

// Where appends a list predicates to the AuthRefreshSessionDelete builder.
func (_d *AuthRefreshSessionDelete) Where(ps ...predicate.AuthRefreshSession) *AuthRefreshSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthRefreshSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthRefreshSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthRefreshSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authrefreshsession.Table, sqlgraph.NewFieldSpec(authrefreshsession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthRefreshSessionDeleteOne is the builder for deleting a single AuthRefreshSession entity.
type AuthRefreshSessionDeleteOne struct {
	_d *AuthRefreshSessionDelete
}

// Where appends a list predicates to the AuthRefreshSessionDelete builder.
func (_d *AuthRefreshSessionDeleteOne) Where(ps ...predicate.AuthRefreshSession) *AuthRefreshSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthRefreshSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authrefreshsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthRefreshSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
