// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"graft/server/modules/auth/ent/authrefreshsession"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 认证刷新令牌会话表（认证模块）
type AuthRefreshSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 关联用户资料的稳定标识
	UserID uint64 `json:"user_id,omitempty"`
	// 刷新令牌唯一标识
	TokenID string `json:"token_id,omitempty"`
	// 刷新令牌失效时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 会话撤销时间，为空表示仍有效
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// 令牌轮换后替代当前会话的新令牌标识
	ReplacedByTokenID *string `json:"replaced_by_token_id,omitempty"`
	// 会话创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 会话最近更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthRefreshSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authrefreshsession.FieldID, authrefreshsession.FieldUserID:
			values[i] = new(sql.NullInt64)
		case authrefreshsession.FieldTokenID, authrefreshsession.FieldReplacedByTokenID:
			values[i] = new(sql.NullString)
		case authrefreshsession.FieldExpiresAt, authrefreshsession.FieldRevokedAt, authrefreshsession.FieldCreatedAt, authrefreshsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthRefreshSession fields.
func (_m *AuthRefreshSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authrefreshsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case authrefreshsession.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case authrefreshsession.FieldTokenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_id", values[i])
			} else if value.Valid {
				_m.TokenID = value.String
			}
		case authrefreshsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case authrefreshsession.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case authrefreshsession.FieldReplacedByTokenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replaced_by_token_id", values[i])
			} else if value.Valid {
				_m.ReplacedByTokenID = new(string)
				*_m.ReplacedByTokenID = value.String
			}
		case authrefreshsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authrefreshsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthRefreshSession.
// This includes values selected through modifiers, order, etc.
func (_m *AuthRefreshSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthRefreshSession.
// Note that you need to call AuthRefreshSession.Unwrap() before calling this method if this AuthRefreshSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthRefreshSession) Update() *AuthRefreshSessionUpdateOne {
	return NewAuthRefreshSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthRefreshSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthRefreshSession) Unwrap() *AuthRefreshSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthRefreshSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthRefreshSession) String() string {
	var builder strings.Builder
	builder.WriteString("AuthRefreshSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("token_id=")
	builder.WriteString(_m.TokenID)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReplacedByTokenID; v != nil {
		builder.WriteString("replaced_by_token_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuthRefreshSessions is a parsable slice of AuthRefreshSession.
type AuthRefreshSessions []*AuthRefreshSession
