// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"graft/server/modules/auth/ent/authcredential"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthCredentialCreate is the builder for creating a AuthCredential entity.
type AuthCredentialCreate struct {
	config
	mutation *AuthCredentialMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AuthCredentialCreate) SetUserID(v uint64) *AuthCredentialCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *AuthCredentialCreate) SetPasswordHash(v string) *AuthCredentialCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *AuthCredentialCreate) SetNillablePasswordHash(v *string) *AuthCredentialCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetMustChangePassword sets the "must_change_password" field.
func (_c *AuthCredentialCreate) SetMustChangePassword(v bool) *AuthCredentialCreate {
	_c.mutation.SetMustChangePassword(v)
	return _c
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_c *AuthCredentialCreate) SetNillableMustChangePassword(v *bool) *AuthCredentialCreate {
	if v != nil {
		_c.SetMustChangePassword(*v)
	}
	return _c
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_c *AuthCredentialCreate) SetPasswordChangedAt(v time.Time) *AuthCredentialCreate {
	_c.mutation.SetPasswordChangedAt(v)
	return _c
}

// SetNillablePasswordChangedAt sets the "password_changed_at" field if the given value is not nil.
func (_c *AuthCredentialCreate) SetNillablePasswordChangedAt(v *time.Time) *AuthCredentialCreate {
	if v != nil {
		_c.SetPasswordChangedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthCredentialCreate) SetCreatedAt(v time.Time) *AuthCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthCredentialCreate) SetNillableCreatedAt(v *time.Time) *AuthCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthCredentialCreate) SetUpdatedAt(v time.Time) *AuthCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthCredentialCreate) SetNillableUpdatedAt(v *time.Time) *AuthCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AuthCredentialMutation object of the builder.
func (_c *AuthCredentialCreate) Mutation() *AuthCredentialMutation {
	return _c.mutation
}

// Save creates the AuthCredential in the database.
func (_c *AuthCredentialCreate) Save(ctx context.Context) (*AuthCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthCredentialCreate) SaveX(ctx context.Context) *AuthCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthCredentialCreate) defaults() {
	if _, ok := _c.mutation.MustChangePassword(); !ok {
		v := authcredential.DefaultMustChangePassword
		_c.mutation.SetMustChangePassword(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthCredentialCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthCredential.user_id"`)}
	}
	if _, ok := _c.mutation.MustChangePassword(); !ok {
		return &ValidationError{Name: "must_change_password", err: errors.New(`ent: missing required field "AuthCredential.must_change_password"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthCredential.updated_at"`)}
	}
	return nil
}

func (_c *AuthCredentialCreate) sqlSave(ctx context.Context) (*AuthCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthCredentialCreate) createSpec() (*AuthCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authcredential.Table, sqlgraph.NewFieldSpec(authcredential.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(authcredential.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(authcredential.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = &value
	}
	if value, ok := _c.mutation.MustChangePassword(); ok {
		_spec.SetField(authcredential.FieldMustChangePassword, field.TypeBool, value)
		_node.MustChangePassword = value
	}
	if value, ok := _c.mutation.PasswordChangedAt(); ok {
		_spec.SetField(authcredential.FieldPasswordChangedAt, field.TypeTime, value)
		_node.PasswordChangedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AuthCredentialCreateBulk is the builder for creating many AuthCredential entities in bulk.
type AuthCredentialCreateBulk struct {
	config
	err      error
	builders []*AuthCredentialCreate
}

// Save creates the AuthCredential entities in the database.
func (_c *AuthCredentialCreateBulk) Save(ctx context.Context) ([]*AuthCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthCredentialCreateBulk) SaveX(ctx context.Context) []*AuthCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
