package store

import authstore "graft/server/plugins/auth/store"

var (
	// ErrRefreshSessionNotFound is kept as a temporary compatibility alias during auth extraction.
	ErrRefreshSessionNotFound = authstore.ErrRefreshSessionNotFound
)

type UserCredential = authstore.UserCredential
type SetPasswordHashInput = authstore.SetPasswordHashInput
type ResetPasswordAndRevokeSessionsInput = authstore.ResetPasswordAndRevokeSessionsInput
type ChangePasswordAndRevokeOtherRefreshSessionsInput = authstore.ChangePasswordAndRevokeOtherRefreshSessionsInput
type EnsureUserCredentialInput = authstore.EnsureUserCredentialInput
type RevokeOtherRefreshSessionsInput = authstore.RevokeOtherRefreshSessionsInput
type RefreshSession = authstore.RefreshSession
type ListActiveRefreshSessionsByUserIDInput = authstore.ListActiveRefreshSessionsByUserIDInput
type CreateRefreshSessionInput = authstore.CreateRefreshSessionInput
type RevokeRefreshSessionInput = authstore.RevokeRefreshSessionInput
type RevokeRefreshSessionsByUserIDInput = authstore.RevokeRefreshSessionsByUserIDInput
type RevokeRefreshSessionByUserIDInput = authstore.RevokeRefreshSessionByUserIDInput
type RotateRefreshSessionInput = authstore.RotateRefreshSessionInput
type PasswordChangeRepository = authstore.PasswordChangeRepository
type AuthRepository = authstore.AuthRepository
